\documentclass[fignum,man]{apa}

\usepackage{Sweave}
\usepackage{apacite}
\usepackage{setspace}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{rotating}
\usepackage{multirow}
\usepackage{todonotes}
\usepackage[hyphens]{url}
\usepackage{longtable}
\usepackage{endfloat}

\widowpenalty=10000
\clubpenalty=10000
\raggedbottom
\newcommand{\helv}[1]{{\Huge\fontfamily{phv}\selectfont{#1}}}

\title{Worldview-motivated rejection of science and the norms of science}
\twoauthors{Stephan Lewandowsky}{Klaus Oberauer}
%or \threeauthors{}{}{}
\twoaffiliations{University of Bristol and University of Western Australia}{University of Zurich}

\abstract{Some scientific propositions are so well established that they are no longer debated
	by the relevant scientific community, 
	such as the fact that greenhouse gas emissions are altering the 
	Earth's climate. In many cases, such scientifically settled issues
	are nonetheless rejected by segments of the public. 
U.S. surveys have repeatedly shown 
	that the rejection of scientific evidence across a broad range of domains is 
	preferentially associated with rightwing or libertarian 
	worldviews, with little evidence for 
	rejection of scientific evidence by people on the political left. 
	We report two preregistered 
	representative surveys (each $N>1000$) 
	that (1)
	sought to explain this apparent political asymmetry and (2)
	continued the search for the rejection of scientific evidence on
	the political left.
	To address the first question, we focused on Merton's classic 
	analysis of 
	the norms of science, such as communism and universalism, 
	which continue to be internalized by the scientific 
	community but which are not readily reconciled with conservative 
	values. Both studies show that people's political worldviews 
	are associated with their attitudes towards those scientific 
	norms, and that those attitudes predict people's 
	acceptance of vaccinations and climate science. 
	The norms 
	of science may thus be in latent conflict with the worldviews of a substantial 
	segment of the public. To address the second question,
	we examined people's views on the role of inheritance in determining
	people's intelligence, given that the belief in the power of
	learning and environmental factors to shape human development is
	a guiding principle of leftwing thought. 
	We find no association between core measures of political worldviews
	and people's view of heritability of intelligence, although two
	subordinate constructs, nationalism and social dominance orientation, were 
	associated with belief in heritability.}

\acknowledgements{Preparation of this paper was facilitated by a  
 Humboldt
Award from the Alexander von Humboldt Foundation to the first
author. This project has also received funding from the European Union’s 
Horizon 2020 research and innovation programme under grant agreement No 964728 (JITSUVAX).
Address correspondence to the first author at the 
School of Psychological Science,
University of Bristol,
12a Priory Road,
Bristol BS8 1TU, United Kingdom. email: stephan.lewandowsky@bristol.ac.uk.
Personal web page: http://www.cogsciwa.com.}

\shorttitle{Worldview and norms of science}
\rightheader{Worldview and norms of science}
\leftheader{Worldview and norms of science}

\ifapamodeman{%
\note{Word count: 8,800 excluding references (approximate count due to use of \LaTeX)

\begin{flushleft}
Stephan Lewandowsky \\
School of Psychological Science and Cabot Institute \\
University of Bristol \\
12a Priory Road \\
Bristol BS8 1TU, United Kingdom \\
stephan.lewandowsky@bristol.ac.uk \\
URL: http://www.cogsciwa.com \\
\end{flushleft}}
}
{% else, i.e., in jou and doc mode
\note{}
}
\begin{document}
\maketitle

<<preamble, echo=FALSE, message=FALSE>>=
knitr::opts_chunk$set(results="hide",echo=FALSE,message=FALSE,error=FALSE)
@
<<doanalysis, echo=FALSE, warning=FALSE, message=FALSE, results='hide', fig.keep='none'>>=
# run the analysis which should generate figures
#source("test.R")
source("C:/Users/Lewan/Documents/Research Projects/Climate Change/religion human special status and science Klaus/Study 1 -- part of original Cognition submission 2019/Q rep sample/Q religion data/religionQualtrics.r")
@
According to Donald Trump, vaccinations cause autism and climate change is a hoax
that was created by the Chinese to make U.S. manufacturing non-competitive \cite{Matthews17}. 
According to others, AIDS is an
invention of the U.S. government \cite{Bogart11}, and now even
the Earth is flat again \cite{Landrum19,Strauss16}. 
Many established scientific propositions that have been accepted
by the relevant
expert communities are subject to public dispute and, sometimes, outright rejection
by sizable segments of the population. For example, some 20\% of the American 
public have been shown to echo Donald Trump's views by declaring that climate 
change ``is a hoax perpetrated by corrupt scientists'' \cite{Lewandowsky13b}. 

Those opinions are not without adverse consequences: Whenever well-established 
medical research
findings are rejected, a detrimental impact on public health 
ensues, as in
the case of anti-vaccination movements \cite{Gangarosa98,Smith07b}. 
When science denial
becomes official government policy, the death toll can run in the
hundreds of thousands, as in the case of South Africa's President Mbeki, who 
refused to accept the link between HIV and AIDS and denied patients access to 
antiretroviral treatments \cite{Chigwedere08}.

There has been increasing research interest in
the psychological variables that explain why people reject scientific facts \cite<for recent 
summaries, see>{Lewandowsky21,Lewandowsky16b}. Two consistent findings have emerged from this
research:
First, general levels of education,
scientific knowledge, and science literacy
are at best modestly predictive of general attitudes and trust
in science
\cite<e.g.,>{Allum08}. Second, 
numerous studies have shown that
people's worldviews, that is their deeply-held beliefs 
about the world and about how society should be 
organized, predict their attitudes towards science across a wide range of 
topics and domains. To date, 
studies conducted mainly in the United States 
have converged on the conclusion that the rejection
of science is primarily associated with rightwing or libertarian 
worldviews. Whether it is climate change \cite<e.g.,>{Hamilton11,Hamilton15b,Hornsey16,Lewandowsky13b}, 
vaccinations \cite<e.g.,>{Hamilton15a,Hornsey18,Kahan10a,Lewandowsky13b,Lewandowsky20g}, 
evolution \cite<e.g.,>{Hamilton15c,Lewandowsky20g},
genetically-modified organisms \cite<e.g.,>{Hamilton15c}, or even
nuclear energy \cite<e.g.,>{Hamilton15c}, people on the political left 
trust scientists more on those issues
and tend to accept the pertinent scientific findings more than
their counterparts on the political right. 


Worldviews have been repeatedly found to override other variables, such as knowledge
and education or science literacy.
For example, polarization on climate change along
political lines has been found to increase with
self-reported knowledge of climate change \cite{Hamilton11},
scientific literacy and numeracy \cite{Kahan12}, and
education \cite{Hamilton15b}. Whereas greater education or
knowledge is associated with increased acceptance of climate science
among liberals, the reverse is true for conservatives.  

Although survey data cannot be generalized
beyond their specific cultural context, the association between 
worldviews and rejection of climate
science and vaccinations has also
been observed in countries other than the United States: The same basic association
between rightwing or libertarian worldviews and rejection of climate science
has been
obtained in Australia \cite{Cook16} and the
United Kingdom \cite{Capstick14}, using a variety  of different
worldview measures. A recent meta-analysis confirmed
the presence of the association across 56 nations for climate
change \cite{Hornsey16}, and across 24 nations 
for vaccinations \cite{Hornsey18}.

The research to date has left open two important
questions: First, what explains the seemingly pervasive 
association between rightwing---but not leftwing---worldviews and the 
rejection of science? 
What underlying explanatory variables, if any, can be identified 
that might explain the propensity for rejection of science by the 
political right? Might the intrinsic attributes of the scientific enterprise
be uniquely challenging to people with rightwing or libertarian
worldviews? Or is the association merely the result of
conflicting imperatives between scientific findings and their economic implications,
as in the case of climate change?
Second, are there any domains in which
the role of worldviews is reversed---that is, do 
liberals reject scientific findings that conservatives or libertarians endorse? 
Is there ``science denial'' somewhere on the political left? 
We address both questions in the present study.
 
\subsection{Attitudinal asymmetry and the nature of science}
In the context of climate change,
the reasons for the strong association
between rightwing worldviews and denial
are easy to understand. 
Climate change is
the result of unfettered fossil-fuel powered economic growth during the last century.
Successful climate mitigation
will require deep cuts to greenhouse gas emissions \cite<e.g.,>{Knutti15}
that 
are not achievable without a significant intervention in the operation of the global
economy, be it through taxes, a price on carbon, or  regulations. 

Climate change therefore presents a vexing
dilemma to people who are emotionally and intellectually vested in
free-market economics: Accept 
the science and accept that unregulated markets can give
rise to problems whose solution requires state intervention, or 
reject the scientific findings and continue operating in the 
belief that unregulated markets are the
best approach to delivering economic prosperity.
The available body of data suggests that many conservatives 
resolve this
dilemma by rejecting the scientific evidence.  
Similar arguments can be advanced in the context of vaccinations: 
libertarians may oppose public-health measures, such as
 mandatory (or nearly-mandatory)
childhood vaccinations as 
government intervention \cite{Kahan10a}. Likewise, evolution might be
opposed for religious reasons, and via the association between religiosity and 
rightwing worldviews \cite{Malka12}, this opposition will
be detected in studies relating worldview to acceptance of evolution.

However, it is less clear why rightwing worldviews would predispose 
people to be more distrustful of scientists even when it comes to 
nuclear power or genetically-modified organisms---both are issues that
mesh well with free markets and free enterprise. 
It is also not immediately clear 
why there has been an ongoing 
gradual erosion  of trust in science 
among conservatives---but not liberals---since the
mid 1970s \cite{Gauchat12}. Whereas
conservatives and liberals did not differ
in their trust in science in the 1970s, by
2010 the polarization had become
quite striking, with liberals retaining  trust in the scientific
community and conservatives having drastically reduced theirs.
Several candidate attitudes 
might be implicated in this general and growing 
distrust of science among conservatives.


\subsubsection{The norms of science}
We first explore the possibility that the---often tacit---norms 
and principles that guide the scientific enterprise might be
less compatible with conservative than liberal worldviews.
Perhaps the most well known and  influential analysis of the norms of science was
articulated by sociologist Robert \citeauthor{Merton42} \citeyear<e.g.,>{Merton42}, who argued that
the results of scientific research should be the 
common property of the scientific community (``communism'');
that knowledge should transcend racial, class, national, or political barriers (``universalism'');  that scientists conduct research
for the benefit of the scientific enterprise rather than for personal 
gain (``disinterestedness''); and that
scientific claims must be exposed to critical scrutiny before being accepted (``organized skepticism''). Survey results suggest that those norms continue to be broadly internalized by the scientific community \cite{Macfarlane08}.
Several of those norms are potentially challenging to conservative worldviews,
and our two studies were designed to explore this potential conflict. The first study focused 
on the scientific norms of communism and universalism, together with other implications of
the scientific enterprise that might be at odds with conservative worldviews. 
The second study explored the full range of Merton's scientific norms. Both studies
examined the association between attitudes towards those norms to the acceptance of
scientific constructs.  

The scientific norms of communism and universalism stand in opposition to nationalism.
Conservatism has long 
been linked to
nationalism and patriotism, at
the expense of embracing cooperative  internationalism \cite<e.g.,>{Kosterman89}.\footnote{ For the purposes of this paper,
we are only concerned with cooperative internationalism, that is the
idea that countries should cooperate multilaterally to solve global problems \cite{Todorov04}.
We are not concerned with another variant of internationalism,
now often referred to as ``Conservative Internationalism'' \cite{Laderman18}, which 
relies on military
strength to achieve global objectives 
and largely eschews multilateralism.}
In a direct examination of the link between nationalism and scientific attitudes, 
\citeA{Tranter17} found that (Australian) self-declared patriots were less likely to accept climate change as happening than citizens who professed less patriotism. In another Australian
sample, \citeA{DevineWright15} similarly found that people who felt attached to their country more than to the Earth as a whole were more likely to deny climate change than people with a global attachment.
\citeA{Krange18} recently reported similar results in a Norwegian sample.
In the U.S.,
\citeA{Ranney16a} reported two experiments
that temporarily reduced participants' nationalism by providing
them with 
``supra-nationalist'' information; that is, information that contextualized
the United States in a community of nations rather than in the more usual
portrayal of American exceptionalism. This intervention 
increased acceptance of climate change by a considerable margin.

There is thus at least tentative evidence that scientific attitudes might be affected by 
a person's degree of patriotism or nationalism, or conversely, by their 
embrace of internationalism.
However, to date those variables have been explored largely in the context
of climate change, which is a global problem whose
resolution
requires international cooperation. The involvement
of nationalism in climate attitudes may therefore
be related to the specific international  attributes
of climate change, rather than reflecting a more general
role of nationalism in the rejection of science
based on its universalist and communist norms.

Our first study therefore included a number
of different scientific constructs in order to establish the breadth
of involvement of nationalism in the rejection of science. 
In particular, we probed attitudes towards climate science, where
we expected nationalism to be implicated
because of the associated global governance issues. We also probed 
other scientific propositions that have no global governance 
implications (vaccinations and heritability of intelligence) where
nationalism would only be implicated indirectly, via its presumed
conflict with the norms of science.
Our first study also probed two further potential
predictor constructs, namely the belief in human
exceptionalism and religiosity, that are potentially in conflict
with scientific norms and findings, and that might help explain
why conservatives are more prone to rejecting scientific findings.
  
\subsubsection{Human exceptionalism}
The idea that humans are exceptional and differ from all other
life forms has been, at least tacitly, at the root of much
Western philosophy and nearly all science from its Cartesian origins 
onward. This anthropocentrism is at the core
of traditional Judeo-Christian thought, which sees the 
human as an
\textit{imago Dei}, an image of God, that is clearly separate from
other beings and nature itself \cite<e.g.,>{Marchesini15}. 
This proclivity for exceptionalism is so widespread that it
arguably has affected scientific practice, and may have
prevented ``the research community from finding
the frame in which humans are ordinary'' \cite[p.~199]{Finlay13}.

A corollary of human exceptionalism vis-\`{a}-vis other species is the 
belief in ``human development''; that is, consumption-based
economic growth to increase living standards and hence human well being
\cite<e.g.,>{Srinivasan16}. Although the
valorization of human wellbeing
is central to this pursuit, it ironically
entails 
harmful effects on 
the environment that ultimately may compromise human well-being.

The role of science vis-\`{a}-vis human exceptionalism 
is ambivalent: On the one hand, without science no human
development on the scale observed during the last century would have
been possible. Science therefore has been a powerful
tool in the pursuit of exceptionalist goals.
On the other hand, the over-arching 
outcome of the centuries of research since the scientific 
revolution has been a diminution of the status of human beings: 
The Earth was considered the center of the universe 
for millennia, whereas we now know our planet to be a rather small 
and insignificant object in a universe
full of an untold number of galaxies. Similarly, 
whereas Saint Augustine could claim that humans were created in 
the image of
God, research has increasingly revealed surprising cognitive
similarities between us and other species.
For example, chimpanzees have been shown to be
capable of altruism  \cite{Warneken06,Warneken07}. Indeed,
chimpanzees may have at least a rudimentary ``theory of mind'' \cite{Karg15}.
Although the boundaries of primate cognition
are still being debated, there is no doubt that
scientific progress---especially 
in evolutionary biology---has placed 
\textit{homo sapiens }within a continuous 
development of species,  eroding 
 support for the notion that humans are exceptional. 

A person with a commitment to human exceptionalism may therefore 
be reluctant to embrace the scientific method or its findings, lest 
it further reduce the human stature in the universe.
In support, \citeA{Gottlieb17}
showed in a number of studies 
that the more people 
thought that a behavior (e.g., recognizing faces, falling in love) was a uniquely human ability, 
the less likely they deemed it to be that science could ever explain that behavior, 
and the  more discomfort they felt at the idea that science might investigate
those phenomena.
Similarly, much research into environmental 
attitudes \cite<e.g.,>{Polonsky14,Rudman13,Whitmarsh11a} has relied on the 
New Environmental Paradigm (NEP) Scale 
\cite{Dunlap00}, which subsumes two factors that are pertinent to anthropocentrism 
and exceptionalism. 
This research has generally found that NEP scores are predictive of attitudes about climate change
 \cite{Whitmarsh11a} and 
behaviors such as pro-environmental purchases \cite{Polonsky14}.
However, we are not aware of any research that has related exceptionalism
to acceptance of science more generally.
We therefore included a measure of human exceptionalism in our first study.

\subsubsection{Religion and science}
There is clear evidence that the rejection of some scientific
propositions is driven by religious beliefs. For example,
\citeA{Miller06c} showed an association between religiosity and 
rejection of evolution across multiple countries.
Similarly, using General Social Survey data, \citeA{Jelen14}
showed that 
membership in an evangelical denomination and a literal
belief in
the authority of the Bible predicted rejection of evolution and stem cell
research, although it was only marginally related to the rejection of climate change.  
This difference between a strong association for evolution and a reduced
magnitude for climate change was replicated by \citeA{Ecklund17}.
Similar results were reported by \citeA{Rutjens17}, who
additionally showed that religious conservatives had particularly low faith in science 
generally and were reluctant to support funding for it. 

However, religion is not necessarily a barrier 
to acceptance of science: Most famously, in June 2015, Pope Francis released
his encyclical \textit{Laudato si}, in which he declared climate mitigation
to be a moral imperative.\footnote{ The encyclical did not 
	shift American public attitudes
about climate change overall. Among those who had heard 
of the encyclical, the Pope's intervention increased polarization: 
concern about climate change was increased among liberals,
but it decreased among
conservatives, who also 
devalued the Pope's credibility on climate issues \cite{Li16a}.}
Moreover, in an Australian sample \cite{Morrison15}, 
Buddhists were found to be
even more concerned about climate change than non-religious respondents
(who in turn were more concerned than Christians).
On balance, therefore, the involvement of religion 
in the rejection of science appears
nuanced and is worthy of further exploration.
Our study therefore also included an assay of religiosity.

\subsection{Science denial on the left?}
Our preceding analysis provided several reasons why the rejection
of science might be expected to be particularly prevalent on the political right.
An empirical test of this analysis should therefore also include a search
for  scientific propositions that, for political or ideological reasons, 
are expected to be in conflict with \textit{leftwing} political views.
Does the general harmony between the norms of science and leftwing worldviews
override the worldview challenge posed by a specific scientific issue? 

Past attempts to assign science denial to the political left 
have focused on genetically-modified (GM) foods and vaccinations, based largely on media
reports 
that claimed left-wing opposition to GM foods \cite<e.g.,>{Shermer13W} and a left-wing
 anti-vaccine stance \cite<e.g.,>{Mooney11W}. Those suggestions
 have not withstood scrutiny: Attitudes towards GM foods
have turned out to be uncorrelated with political views \cite{Lewandowsky13b},
and distrust of GM scientists has turned out to be  greater 
on the political right than the left \cite{Hamilton15c}. Likewise, 
research has linked opposition to mandatory human-papillomavirus (HPV) immunizations 
against cervical cancer to free-market and individualistic worldviews \cite{Kahan10a},
and general skepticism of vaccinations has also been found to be particularly prevalent among
free-market enthusiasts \cite{Lewandowsky13b,Lewandowsky20g}. 
Endorsement of complementary and alternative medicine (CAM) has also been found to be
higher among conservatives than liberals \cite{Lewandowsky20g}, contrary to 
anecdotal claims of a symbiosis between alternative medicine and 
other left-wing ideas under the umbrella of ``New Age'' thinking \cite{Keshet09}.


Here, our search for science denial on the political left focuses on people's ideas about the 
environmental determinants of intelligence. The belief in the ability to improve people
and their circumstances, often known as meliorism, 
is at the heart of liberalism \cite<e.g.,>{Castagno17,Porter13}, 
whereas disbelief or skepticism in that possibility
characterizes conservatives.
Accordingly, there is evidence that higher ratings of social conservatism 
are associated
with lower ratings of the possibility of general human
improvement \cite{Miller99}. 
In the specific context of intelligence,
people have been shown to be 
split on whether they see intelligence as 
fixed and trait-like ``entities'' or as malleable and ``incremental'' 
processes \cite{Dweck95}.
There is evidence that political attitudes affect people's support
for educational policies that rest on the view that intelligence is malleable. For
example, liberal (as opposed to conservative) participants are more likely to support 
policies such as an equal distribution of property taxes across school districts,
and this support is
further amplified by an experimental manipulation that
emphasizes that most
people have the potential to become highly intelligent \cite{Rattan12}.

Those optimistic attitudes stand in at least partial conflict with a large
body of evidence that reveals environmental influences on intelligence to be quite 
limited. First, there is little evidence that intelligence can be boosted
by training. Although 
two recent meta-analyses have suggested that
fluid intelligence \textit{can} be improved by extensive training on 
a variety of other
tasks \cite{Au15,Karbach14}, those results have been challenged by
critics who argued that any beneficial
effects disappear when an appropriate control 
group is used \cite{Dougherty16,MelbyLervag16}.
All meta-analyses agree that, if there is an effect of training on 
intelligence at all, it is fairly small.

Second, individual differences in intelligence are to a large 
part related to genetic differences, with current
estimates of heritability hovering around 50\% 
\cite{Hill18,Polderman15, Sauce18}. Although these estimates
vary across studies and with variables such as the 
age of the subject population, there is no credible 
evidence that would deny a 
notable role of heritability in determining people's intelligence. 
Both our studies therefore included items that queried
people's acceptance of the heritability of intelligence
and its limited malleability. We
expected those items to be particularly challenging to 
people with left-wing political views. We would therefore
expect a positive association with indicators of conservatism
and endorsement of the heritability construct. 

\section{Study 1}

The first study measured 
4 attitudinal constructs and related them to people's
beliefs about 3 scientific issues. 
The first attitudinal construct, nationalism, touches
directly on the communist and universalist norms of science. The second
construct, 
human exceptionalism, provided a potential window into the discomfort
that might arise from science increasingly questioning the 
often-presumed uniqueness of human beings.
The final two constructs, religiosity and
free-market attitudes, constitute two important 
strands of conservative attitudes \cite{Everett13}
and are established statistical 
proxies for general conservatism (e.g., free-market 
endorsement is strongly associated with
conservatism; $r=.76$, \citeNP{Lewandowsky13b}). 
All constructs were scored such that greater
values reflected greater endorsement.

The scientific attitudes we examined covered a broad range of domains.
We probed attitudes towards climate
change and its human causes, the safety and efficacy of 
vaccinations, and whether intelligence is genetically determined 
(called \textit{IQ Heritable}
for brevity from here on). These constructs
were also scored to map greater values into greater endorsement.
For climate change and vaccination, greater endorsement 
also implied greater acceptance of the scientific ``gold standard'':
the items were designed such that full acceptance
of the relevant scientific knowledge would translate into
complete endorsement. For IQ Heritable, the ``gold standard''
is less clearly defined because heritability is a matter of
degree and the ground truth is not precisely known. We
are therefore more concerned with associations between IQ Heritable
and other constructs rather than specific levels of endorsement.

The sampling plan and procedure as well as an analysis
plan were preregistered before data collection
commenced. The preregistration document including a complete
copy of the survey and a proposed analysis script in R
can be found at \url{https://osf.io/su8nf/}.

\subsection{Method}

\subsubsection{Materials}
The survey comprised 46 items, broken
down into 3 demographic queries presented at the outset (age, gender, and 
the age of acquisition of English), 39 items to measure 
our core constructs, 2 items that
targeted claims that climate change is a ``hoax'' (not analyzed
here), and two items that served as attention filter. 
The first attention filter asked people to identify which of a list of 5 items
was not an animal, and the second attention filter consisted of 
a renewed query of participants' age at the end of the survey.

The 39 core items and the first attention filter were presented in a 
different random order for each participant.
Table~S1
provides a verbatim list of the 39 core survey items together
with brief labels (e.g., \textit{HumConsc} for ``Humans are the only living 
beings who are conscious'') that are used for presentation of
the results. For illustration,
Table~\ref{tab:itemoverview} shows one representative items for
each construct used across the two studies.

\begin{table} 
%	\renewcommand\arraystretch{1}
	\caption{Sample items for all constructs used in both studies and their short names}
	\label{tab:itemoverview}
	{\setstretch{1.4}
	\begin{tabular}{p{.2\linewidth} p{.18\linewidth} p{.62\linewidth}} %tab:itemoverview
		\hline
		Construct & Item name & \multicolumn{1}{c}{Item}  \\
		\hline
		\multicolumn{3}{c}{Study 1}\\
		\hline
		Exceptionalism & \emph{HumConsc} & Humans are the only living beings who are conscious. \\
		Nationalism & \emph{Allegiance} & Every human must have an allegiance to one country and one country only. \\
		IQ Heritable & \emph{IQGen} & When people differ in intelligence, it is mostly due to differences in their genetic endowment.  \\
		Religiosity & 	\emph{RelComf} & Religion gives me a great amount of comfort and security in my life. \\
		Free market & \emph{FMMoreImp}&The preservation of the free market system is more important than localized environmental concerns.  \\
		Climate science & 	\emph{CO2causesCC} & Human CO2 emissions cause climate change. \\ 
		Vaccinations & 	\emph{VaxSafe} & I believe that vaccines are a safe and reliable way to
		help avert the spread of preventable diseases. \\	
		\hline
		\multicolumn{3}{c}{Study 2 (new constructs only)}\\
		\hline
		Norms of Science & \emph{NOR\_COM1} & Scientific findings should be available to everybody everywhere in the world
		\\
		&\textit{NOR\_DIS1}  & Scientists should put evidence ahead of their own views	\\
		&\textit{NOR\_SCEP1}  & Scientists should always keep an open mind and
		be prepared to change their conclusions if new evidence comes along	\\
		&\textit{NOR\_UNIV1}  & The truth of a scientific discovery does not depend on the nationality, gender, race, or faith of the scientist making it
		\\
		Conservatism & 	\textit{POL\_CONS1} &	People are better off in a free market economy \\
		Social Dominance Orientation &		\textit{SDO1} &	An ideal society requires some groups to be on top and others to be on the bottom \\
		
		\hline
	\end{tabular}}
\end{table}

\setstretch{2}

The items for human exceptionalism, nationalism, and heritability of 
intelligence were designed by
the authors for this study. The items for the free-market, vaccinations, and climate-science constructs
were taken from our earlier research \cite<e.g.,>{Lewandowsky13b}. 
All items for those constructs used a 7-point response scale ranging 
from ``Strongly agree'' to ``Strongly disagree''.
The religiosity items
were taken from \cite{Rohrbaugh75} and retained the original 5-point response scales (see Table~S1), with the exception 
of \textit{RelComf} which used the 7-point scale (``Strongly agree'' -- ``Strongly disagree'') to
retain consistency with all other items querying agreement.

\subsubsection{Ethics statement}
The Ethics Committee of the Department of Psychology
at the University of Zurich approved the study. 
The survey was prefixed
by an introductory information sheet outlining the research.
Participants indicated their informed consent after reading this information sheet 
by 
a mouse click, which commenced presentation of the
survey questions.

\subsubsection{Participants and procedure}

A sample of 1,000 U.S. residents 18 years and older was recruited during March 2017
via electronic invitations by Qualtrics.com, a firm that
specializes in representative internet surveys. 
Participants were
drawn from a completely bipartisan panel of more than 5.5 million
U.S. residents (as of January 2013), via propensity weighting to
ensure representativeness in terms of gender, age, and income.
Participants were compensated by Qualtrics using the company's
standard reward scheme.


\subsection{Results}

The final sample included \Sexpr{dim(relig)[1]} responses that passed the Qualtrics
quality checks (including the two attention filters) and were delivered to the authors.
This data file can be accessed at \url{https://osf.io/bg4fb/} (potentially identifying information
has been removed).
Although our preregistered analysis plan did not specify any further exclusion criteria,
we discovered that several participants responded identically (before reverse-coding)
to all
items for one or more constructs. We deemed this to be indicative of potential
inattention and therefore eliminated any participant who responded identically 
to all items for more than one construct.
After exclusion, \Sexpr{dim(relig15)[1]}
observations 
were retained for analysis. 
The final sample included \Sexpr{males} men and \Sexpr{females} women, with a mean age of 
\Sexpr{mage}
 (median \Sexpr{mdage};
range \Sexpr{minage}--\Sexpr{maxage}). Only \Sexpr{lateEnglish} 
participants had learned English less than 5 years ago;
they were retained for analysis. 
The R scripts for all analyses reported in this article 
can be found at \url{https://git.io/fpEYo}, together with the \LaTeX ~source file 
that weaves the results of the analysis in R directly into the paper. 
The online supplement (Table~S2 and Figure~S1) summarize
the raw responses and distribution of composite scores.

\subsubsection{Latent variable modeling}
Our
preregistered analysis plan identified structural equation modeling (SEM)
as our principal analysis technique. 
Thus, each construct of interest was represented by a 
latent variable that was estimated from the 
responses to the corresponding multiple items. Latent variables are not
directly observable but have the advantage of avoiding 
attenuation of the observed effects through
measurement error \cite{Coffman05}. 
Alternative methods, such as multiple regression based on composite scores 
with imperfect reliability, yield results that are more prone to 
measurement error, rendering their interpretation problematic \cite{Osborne02}.
The analysis plan did not
specify particular models for exploration, other than that we
would seek to predict endorsement of climate science and of vaccination attitudes, and attitudes towards 
heritability of intelligence, from the other constructs. Our
latent variable modeling thus conformed to the analysis plan without being 
exactly prescribed by it.

SEM models with more than 20 indicator variables (i.e., items) are often 
too large to achieve adequate levels of model fit \cite{Bentler87}.
One way to overcome this problem is by averaging the item scores measuring 
each construct into a single-indicator 
variable for SEM, a procedure known as item parceling.
One criticism of item parceling is that it may obscure multi-dimensionality \cite{Little02}. 
To preempt this criticism, we first modeled the latent variable for each construct
based on all of its respective items
to determine its dimensionality.
All SEM was conducted using the \textit{lavaan} package in R \cite{Rosseel12}.

\subsubsection{Measurement models}
Six of the constructs were found to exhibit an essentially uni-dimensional
structure, although in most cases one 
correlation between the residuals of two items
had to be
added to the single-factor model to achieve a satisfactory fit.
Table~\ref{tab:indicatormodels} reports the fit statistics for  those 
6 measurement models. For the three constructs that
had been employed in previous research \cite{Lewandowsky13b}, 
the fit statistics were similar and the
correlated residuals involved the same items as before.
For the nationalism construct, the item \textit{IntBigProb}  
was dropped from
the model because it did not load onto the latent variable. The model with 
the remaining 6 items fit very well with a single correlated residual.

\begin{sidewaystable} %tab:indicatormodels
\setstretch{2}
\caption{Model fit indices associated with the
	measurement models for all uni-dimensional constructs in Study~1}
\label{tab:indicatormodels}
%\centering
\begin{tabular}{l rrrrrr l}
\thickline
\multicolumn{1}{c}{Construct}   & $\chi^2$ & $df$ & SRMR & CFI & RMSEA & \multicolumn{1}{c}{90\% CI} & \multicolumn{1}{c}{Correlated residuals} \\
\hline

Exceptionalism &  
\Sexpr{round(as.numeric(humspecgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(humspecgof["df"]))} & 
\Sexpr{round(as.numeric(humspecgof["srmr"]),3)} & 
 \Sexpr{round(as.numeric(humspecgof["cfi"]),3)} & 
 \Sexpr{round(as.numeric(humspecgof["rmsea"]),3)} &
 \Sexpr{round(as.numeric(humspecgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(humspecgof["rmsea.ci.upper"]),3)}  & 
 \textit{HumRational}  $\leftrightarrow$  \textit{EarthHierar}   \\
 
Nationalism & 
\Sexpr{round(as.numeric(internatgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(internatgof["df"]))} & 
\Sexpr{round(as.numeric(internatgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(internatgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(internatgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(internatgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(internatgof["rmsea.ci.upper"]),3)}  & 
\textit{IntEnjoy} $\leftrightarrow$ \textit{IntWeb}  \\

Religiosity & 
\Sexpr{round(as.numeric(religgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(religgof["df"]))} & 
\Sexpr{round(as.numeric(religgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(religgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(religgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(religgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(religgof["rmsea.ci.upper"]),3)}  & 
 \multicolumn{1}{c}{---} \\
 
Free market & 
\Sexpr{round(as.numeric(fmgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(fmgof["df"]))} & 
\Sexpr{round(as.numeric(fmgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(fmgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(fmgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(fmgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(fmgof["rmsea.ci.upper"]),3)}  & 
\textit{FMUnresBest} $\leftrightarrow$ \textit{FMMoreImp} \\

Climate science & 
\Sexpr{round(as.numeric(climategof["chisq"]),2)} & 
\Sexpr{round(as.numeric(climategof["df"]))} & 
\Sexpr{round(as.numeric(climategof["srmr"]),3)} & 
\Sexpr{round(as.numeric(climategof["cfi"]),3)} & 
\Sexpr{round(as.numeric(climategof["rmsea"]),3)} &
\Sexpr{round(as.numeric(climategof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(climategof["rmsea.ci.upper"]),3)}  & 
 \textit{CNatFluct} $\leftrightarrow$ \textit{HumansInsign}  \\

Vaccinations & 
\Sexpr{round(as.numeric(vaxgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(vaxgof["df"]))} & 
\Sexpr{round(as.numeric(vaxgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(vaxgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(vaxgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(vaxgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(vaxgof["rmsea.ci.upper"]),3)}  & 
 \textit{VaxNegSide} $\leftrightarrow$  \textit{VaxRisky} \\
\thickline
\end{tabular}
\end{sidewaystable}

Unlike for the other constructs, it proved impossible to create a simple
unidimensional measurement model
for the IQ Heritable construct. This difficulty arose because the items of opposing polarity
could not be assigned to a single factor. Instead, items that were phrased such that endorsement 
implied environmental determinants (\textit{IQStim,  
IQAdopt,  
IQEd,  
IQUpbring}), and those whose endorsement implied heritability (\textit{IQGen,  
IQTwins,  
IQParents}), could each be modeled by a single-factor model that fit extremely well,
but with only a modest correlation between the two factors
when combined into a two-factor model, $r=\Sexpr{round(twocfacIQcor[2,1],2)}$,
$p < \Sexpr{round(max(.0001,twocfacIQp[2,1]),4)}$. 
To model all items together,  
we therefore created 
a hierarchical two-factor model, in which the
component factors loaded onto a second-order factor, with the loadings of the 
two component factors constrained to be equal. That second-order factor reflects 
whatever variance is shared by the component factors, beyond the ``nuisance''
variance arising from reverse scoring. Because the loadings were constrained
to be equal, items of each polarity were given equal weight.

This hierarchical model fit very well, $\chi^2(\Sexpr{twofacIQgof["df"]})=\Sexpr{round(twofacIQgof["chisq"],2)}$; 
SRMR=\Sexpr{round(twofacIQgof["srmr"],3)}; CFI=\Sexpr{round(twofacIQgof["cfi"],3)}; 
RMSEA=\Sexpr{round(twofacIQgof["rmsea"],3)} (90\% CI:
 \Sexpr{round(twofacIQgof["rmsea.ci.lower"],3)}--\Sexpr{round(twofacIQgof["rmsea.ci.upper"],3)}).\footnote{ 
Evaluating the fit of a structural equation model involves is a complex judgment based on a number of
available fit indices \cite{Hu99}. The $\chi^2$ statistic compares the goodness of fit between the obtained
covariance matrix and the predicted matrix derived from the model, where a significant test
indicates model \textit{misfit}. The $\chi^2$ statistic is rarely used to make decisions about fit because
for models based on more than 
400 cases, the $\chi^2$ is almost always statistically significant \cite{Kenny20}. In addition,
the value of the statistic is also affected by the magnitude of the correlations in the model, with
larger correlations giving rise to poorer fit \cite{Kenny20}. For these reasons, researchers
have focused on alternative measures of fit. We report three additional measures:
(a) The Comparative Fit Index (CFI), which is an incremental fit index that can be interpreted
in a manner analogous to $R^2$, with 0 representing complete lack of fit and 1 a perfect fit. 
Values of CFI in excess of .90 or .95 are considered to indicate a good fit \cite{Hu99}. 

(b) The Standardized Root Mean Square Residual (SRMR) which represents the standardized difference 
between observed and predicted correlations. A value of zero indicates perfect fit and values less than .08 
are generally considered a good fit \cite{Hu99}. 

(c) The Root Mean Square Error of Approximation (RMSEA) is an absolute measure of fit that
is derived from  $\chi^2$ and considers sample size and model complexity. Lower values of RMSEA denote
better fit, and conventionally a 90\% confidence interval of the estimate is reported, 
where ideally the lower value is no higher than .05 and the upper value less than .08 
\cite{Kenny20}. 
}
 Because 
 the IQ Heritable construct required a more 
 complex model, thus defying the requirements for item-parceling, we first
 focus on the single-indicator latent variables for the other constructs.

\subsubsection{Single-indicator latent variable models}
We modeled the 6 unidimensional
constructs via single-indicator latent variables \cite{Hayduk96,Joreskog82}.
In single-indicator models, each latent variable is defined 
by one indicator consisting of an equally-weighted composite 
of the relevant items (i.e., the mean of the item scores).
The supplement provides further details about the single-indicator
models, including summary and fit statistics (Table~S3).

The top panel of Table~\ref{tab:lvcor} shows the correlation 
matrix for the 6 single-indicator latent variables. 
All correlations
were significant ($p < .0001$) with the exception of
the correlation between \Sexpr{rownames(pvals2tailed)[maxloc[1]]} and
\Sexpr{colnames(pvals2tailed)[maxloc[2]]}, $p=\Sexpr{round(maxpval,3)}$.
The results replicate previous research, with a strong
negative correlation between endorsement of free markets and acceptance
of climate science and a smaller negative correlation between
free market and vaccinations. Both sign and 
magnitude of those correlations mesh well with previous research
\cite{Lewandowsky13b}.

\begin{sidewaystable}[!htbp] \centering 
\setstretch{2}
\caption{Correlations among 6 unidimensional latent variables in Study~1} 
\label{tab:lvcor} 
\begin{tabular}{@{\extracolsep{2pt}} l cccccc} 
\\[-1.2ex]\hline 
\hline \\[-1.8ex] 

\input{_t.lvcor.tex}

%next panel has the hierarchical IQ
\hline
\input{_t.IQcor.tex}

\hline \\[-1.8ex] 
\end{tabular} 
\end{sidewaystable}

The bottom panel of Table~\ref{tab:lvcor} contains the correlations between the
IQ Heritable  construct (represented by the second-order factor
in the hierarchical model) 
and the single-indicator latent variables for the 
other constructs. 
All correlations are quite modest, with only that involving \Sexpr{twofacsigcorrs[1]}
exceeding the significance threshold.
Notably, the correlations with free-market endorsement and religiosity, our proxies
 for political
attitudes, were negligible.

The results in the table that are most novel and relevant 
involve the Exceptionalism, Nationalism, and Religiosity constructs. 
In line with our expectation that the norms of 
science challenge conservative worldviews, greater 
religiosity and endorsement of the free market
were also associated with greater nationalism. 
Nationalism, in turn, was associated with reduced acceptance
of two of our scientific constructs (climate and vaccinations), but conversely,
it was associated with increased belief that intelligence is heritable.
Similarly, the belief in human exceptionalism was 
positively associated with religiosity and belief in the free market,
but negatively with the three scientific constructs, although
only one of those correlations, with climate, reached significance.
The positive associations between Exceptionalism and 
our proxies for conservatism are in line with previous
research that has found an association between aspects of right-wing
thought and ``speciesism'', that is 
support for the exploitation of animals to satisfy
human interests \cite{Dhont14a,Dhont16}.
The strong association with Nationalism in particular
mirrors prior work showing that dominance-based attitudes 
correlate highly with the view that humans are superior
to other beings \cite{Dhont16}.

\subsubsection{Predictive models}
We next identified individual predictive models for each of the three 
scientific constructs.
In each case, we first fit a full model involving all potential predictor 
constructs (human exceptionalism, nationalism, religiosity, and free-market endorsement)
and then eliminated predictors until we found the simplest
possible model that did not incur a significant loss of fit
in comparison to more complex models. 
Table~\ref{tab:predmodelcomp} shows, for each scientific construct, 
the fit statistics for 
the simplest model and its predictors. Note that the fit of the predictor model for IQ Heritable is poor. 

\begin{sidewaystable} %tab:indicatormodels
\setstretch{2}	
\caption{Model fit indices and predictors associated with the 
	simplest predictive model for each scientific construct in Study~1}
\label{tab:predmodelcomp}
%\centering
\begin{tabular}{l rrrrrr l}
\thickline
\multicolumn{1}{c}{Construct}   & $\chi^2$ & $df$ & SRMR & CFI & RMSEA & \multicolumn{1}{c}{90\% CI} & \multicolumn{1}{c}{Predictors} \\
\hline
IQ Heritable &
\Sexpr{round(as.numeric(fitsm2fIQgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(fitsm2fIQgof["df"]))} & 
\Sexpr{round(as.numeric(fitsm2fIQgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(fitsm2fIQgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(fitsm2fIQgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(fitsm2fIQgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(fitsm2fIQgof["rmsea.ci.upper"]),3)}  & Nationalism \\


Climate & 
\Sexpr{round(as.numeric(smclimgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(smclimgof["df"]))} & 
\Sexpr{round(as.numeric(smclimgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(smclimgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(smclimgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(smclimgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(smclimgof["rmsea.ci.upper"]),3)}  & Nationalism; free market \\


Vaccinations\tabfnm{{\textit{a}}} & 
\Sexpr{round(as.numeric(smvaxgof["chisq"]),2)} & 
\Sexpr{round(as.numeric(smvaxgof["df"]))} & 
\Sexpr{round(as.numeric(smvaxgof["srmr"]),3)} & 
\Sexpr{round(as.numeric(smvaxgof["cfi"]),3)} & 
\Sexpr{round(as.numeric(smvaxgof["rmsea"]),3)} &
\Sexpr{round(as.numeric(smvaxgof["rmsea.ci.lower"]),3)} -- 
\Sexpr{round(as.numeric(smvaxgof["rmsea.ci.upper"]),3)}  & Nationalism; free market; religiosity\\

	\thickline
\end{tabular}
\tabfnt{\textit{a}}{ The vaccination model suffered a marginally significant loss of fit when Exceptionalism was
removed. We present the smaller model because it fits very well.}
\end{sidewaystable}

For a final unifying model we 
sought to predict all scientific constructs simultaneously. 
Using the same approach as before, we eliminated predictors from the full
model until we found the simplest
possible model that did not incur a significant loss of fit.
This overall model is shown in Figure~\ref{fig:finalSEM}.
The model fit acceptably well, $\chi^2(\Sexpr{finalmodelgof["df"]})=\Sexpr{round(finalmodelgof["chisq"],2)}$; 
$p < \Sexpr{round(finalmodelgof["pvalue"]+.0001,4)}$; 
SRMR=\Sexpr{round(finalmodelgof["srmr"],3)}; CFI=\Sexpr{round(finalmodelgof["cfi"],3)}; 
RMSEA=\Sexpr{round(finalmodelgof["rmsea"],3)} (90\% CI:
\Sexpr{round(finalmodelgof["rmsea.ci.lower"],3)}--
\Sexpr{round(finalmodelgof["rmsea.ci.upper"],3)}).

\begin{figure}[tp] %fig:final2fSEM
\fitfigure{final2fSEM.pdf}
\caption{Final predictive structural equation model for Study~1. 
	All links and correlations shown are 
	standardized and significant; all $p < .0001$ unless shown otherwise
	in the figure. Negative values are highlighted by gray shading.
	Indicator variables and their loadings, and disturbances on endogenous 
	factors as well as the first-order factors for the IQ Heritable
	construct
	are not
	shown. Links between latent variables that are not shown are 
	not significant or constrained to zero.
	Loadings and variances of single-indicator latent 
	variables are reported in Tables~\ref{tab:indicatormodels}
	and~S3.}
\label{fig:finalSEM}
\end{figure}


\subsection{Discussion}

The first study explored two issues:
The role of the norms of science---in particular its
universality and communism---in determining
people's attitudes towards scientific propositions, 
and whether leftwing worldviews would lead people
to reject 
the clear evidence for a heritability component
in determining individual differences in intelligence.
Our results cast light on both issues.

Concerning the role of norms, 
we observed strong positive correlations between
nationalism---a construct that is in intrinsic opposition
to the universality and communality of science---and our proxies 
for conservatism, free-market attitudes and
religion.  
Moreover, nationalism predicted reduced acceptance of two
scientific issues, relating to climate and vaccinations, suggesting
that when people's attitudes mesh well with the 
tacit norms of science (i.e., by rejecting nationalism), 
they are also more likely to endorse scientific
propositions.  
The negative impact of nationalism on vaccinations is particularly
notable because vaccinations typically do not require any 
overt international cooperation (the data were collected before
the COVID-19 pandemic). 
Another notable aspect of the results is the positive association
between Nationalism and IQ heritable. This associations is explainable 
by the theme of an invariant hierarchy among humans that suffuses both nationalism 
(at the level of countries) and the idea of heritability of intelligence 
(at the level of individuals). We explore this further in the next study.

We found limited support for our notion that belief in human exceptionalism
would predispose people to be more skeptical in their acceptance of scientific
propositions. Exceptionalism was negatively associated with acceptance of
climate change, although it was unrelated to IQ Heritable and, in the 
final predictive model (Figure~\ref{fig:finalSEM}), it
was a small but positive predictor of acceptance of vaccination.

At the level of pairwise correlations, our 
results are consonant with the negative
associations between religiosity and 
acceptance of climate change, and between religiosity
and endorsement of vaccination reported by 
\citeA{Rutjens17}.\footnote{ \citeA{Rutjens17} used
	three different measures of religiosity, not all of which correlated
	equally with climate skepticism and vaccination skepticism. However,
	the broadly negative relationship between measures of religiosity and
	attitudes towards those two important scientific issues was 
	replicated here.}
In the final predictive model, religiosity was 
still negatively associated with Vaccinations,
although it did not contribute directly to explaining attitudes towards climate
change or the heritability of intelligence.

Turning to the heritability of intelligence, 
we found 
no associations involving religiosity or free-market
attitudes, two powerful proxies for conservatism. 
The only hint in our data that people on the left might me more inclined to 
think that intelligence can be shaped by the environment arises
from the positive association between nationalism (which is
less prevalent among people on the left) and heritability.
These results must, however, be interpreted with caution.
The IQ Heritable construct
turned out not to be estimable by a uni-dimensional measurement model.
Unlike for the other constructs,
the polarity of the items exerted a major influence, and standard
reverse scoring was insufficient to unify people's responses under
a single factor. 
We instead had to construct a hierarchical two-factor model to accommodate
polarity, and used the second-order factor in our SEM analyses. 
That factor captured the variance that was shared
by all items, thus justifying its use in our further modeling. Nonetheless,
some degree of skepticism might be in order when
interpreting the IQ Heritable construct (e.g.,
the fit of the simple predictive model for that construct was
poor by some measures; see Table~\ref{tab:predmodelcomp}).
Our conclusion that attitudes towards intelligence are largely independent of
political worldviews must therefore remain provisional and is in need
of further empirical scrutiny. 

In summary, the first study again failed to find a notable association between left-leaning
political views and potential rejection of scientific evidence, in this case relating to 
the heritability of intelligence. The first study also provided several
glimpses into the possibility that conservative political leanings may be in
intrinsic conflict with the norms of the scientific enterprise, in particular
its universality and communism. The purpose of the next study was to solidify
those glimpses into a more direct examination of the relationship
between scientific norms and political views.

\section{Study 2}

The second study again related 
beliefs about the same scientific issues 
to a number of potential predictors.
Based on the results of Study~1 and pilot testing, the items probing
beliefs about heritability of intelligence were revised in
order to achieve unidimensionality. 

Unlike Study~1, we used a more direct measure of people's attitudes
towards the norms of science by developing items that targeted
the 4 major norms (communism, disinterestedness, 
scepticism, and universality; \citeNP{Merton42}). 
Table~\ref{tab:itemoverview} provides sample test items for each of those
4 norms (the complete list is in Table~S4).
We also replaced 
free-market attitudes with a broader measure of conservatism. 
Although free-market attitudes tend to be highly correlated with
conservatism \cite{Lewandowsky13b}, economic libertarianism 
and social conservatism form two distinct strands of
conservatism \cite{Everett13}. We therefore used a scale that 
bridged those two strands and is known to be
unidimensional \cite{Lewandowsky21c}.
 
Finally, we replaced religiosity and Exceptionalism by
an individual-differences variable that
measures people's preferences for 
group-based social hierarchies, known as social dominance orientation (SDO).
There were two reasons for this choice:
First, previous research has identified
SDO as a driver of climate denial that is sometimes
sufficiently powerful to mediate, and render
non-significant, the effects of conservatism more generally \cite{Jylha15,Jylha16,Milfont13}.
Second, and more important, SDO taps sentiments that are similar to 
nationalism but at the level of groups within a country. 
To the extent that endorsement of the
heritability of intelligence reflects the belief that
groups or nations should be ranked along a hierarchy,
we would therefore expect SDO to be a predictor 
of the IQ construct, similar to Nationalism in Study~1. 

The sampling plan, procedure, and analysis
plan were preregistered before data collection
commenced. 
The preregistration can be found at \url{https://osf.io/c8qfx}.

<<doanalysis2, echo=FALSE, warning=FALSE, message=FALSE, results='hide', fig.keep='none'>>=
source("C:/Users/Lewan/Documents/Research Projects/Climate Change/religion human special status and science Klaus/Study 2 -- for revision/qualtrics details and data study 2/norms2Q.r")
@

\subsection{Method}

\subsubsection{Materials and participants}

The survey comprised 47 items, broken
down into 2 demographic queries presented at the outset (age and gender), 
2 attention filters, and 
43 items to measure the attitudinal constructs (see Table~S4).
The attention filters queried people's agreement with the statements
that ``the Earth orbits around the moon'' and ``the moon orbits around the Earth''.
The 43 core items and the attention filters were presented in a 
different random order for each participant.
All core items and attention filters used a 7-point 
response scale ranging 
from ``Strongly disagree'' to ``Strongly agree'', with the exception of
one of the conservatism items (\textit{POL\_CONS5}), which used
an 11-point scale (see Table~S4).

Items for climate science and vaccinations were identical to Study~1, and
some of the items for heritability of intelligence were also re-used
from Study~1. The conservatism items were used in
previous related research \cite<see>[for details]{Lewandowsky21c}. 
Social Dominance Orientation (SDO) was measured using the SDO$_{7(s)}$ scale
\cite[Appendix B]{Ho15}. All constructs were scored such that
greater values represented greater endorsement. 

A new representative sample of 1,000 U.S. residents 18 years and older was requested
from Qualtrics
during March 2019.

\subsubsection{Ethics statement}
The Ethics Committee of the Faculty of Science at
the University of Bristol approved the study. 
Participants again indicated their informed consent after reading an 
information sheet that prefixed the survey.

\subsection{Results and discussion}

The final sample delivered by Qualtrics 
included \Sexpr{dim(newNorms)[1]} responses that passed the Qualtrics
quality checks (including the two attention filters).  
This data file can be accessed at \url{https://osf.io/4wy6m/} (potentially identifying information has been removed).
We again eliminated any participant who responded identically (before
reverse scoring)
to all items for more than one construct
($N=$ \Sexpr{as.numeric(table(rowSums(keyhitters))[3])}), 
yielding a final set of \Sexpr{dim(newNorms1.5)[1]}
observations for analysis. 
The final sample included \Sexpr{males2} men and \Sexpr{females2} women 
(\Sexpr{nonbin2} nonbinary), with a mean age of 
\Sexpr{mage2}
(median \Sexpr{mdage2};
range \Sexpr{minage2}--\Sexpr{maxage2}).
Table~S5 and Figure~S2 summarize the raw responses and show the distributions
of composite scores.

\subsubsection{Measurement models and single-indicator models}
We followed the same approach as in Study~1 to construct single-indicator
latent variable models after establishing unidimensionality.


For the norms of science construct, we first formed composites of the
items in the 4 subscales (communism, disinterestedness, scepticism, and universality),
and those 4 composites were then used as indicator variables for the measurement
model. 
Because the expected relationship between political views and the norms of
science were of particular interest, we first considered the correlations
between conservatism and the 4 subscales (Table~\ref{tab:normcors}).
The table shows that greater conservatism was associated with
reduced endorsement of the norms of science overall (bottom row)
and with reduced endorsement of 3 out of 4 of the subscales.
Only skepticism appeared to be apolitical and was not 
associated with the conservatism scale. Because 
the measurement model for norms based on the 4 composites for the subscales 
fit extremely well (Table~\ref{tab:indicatormodels2}), and because
conservatism was strongly associated with reduced endorsement of
norms overall,
we do not differentiate between the subscales from here on.

\begin{table} 
	\setstretch{2}
	\caption{Correlations between conservatism and individual scientific norms in Study~2} 
	\label{tab:normcors} 
	\begin{tabular}{@{\extracolsep{2pt}} l rr rr rrr} 
		
		\thickline
		& \multicolumn{1}{c}{Conservatism}    & \multicolumn{1}{c}{Universalism}  & \multicolumn{1}{c}{Disinterestedness}  
		& \multicolumn{1}{c}{Communism}  & \multicolumn{1}{c}{Scepticism}  \\
		
		\hline 
		
		\input{_t.normcors.tex}
		
		\hline 
	\end{tabular} 
	\tabfnt{}{\textit{Note}. All correlations are significant at $p < .0001$, with the exception of Conservatism $\times$ Scepticism, for which $p > .1$. The All norms score was obtained by averaging each participant's responses across all items pertaining
	to norms. Scores for the individual norms were obtained by averaging responses within each relevant subscale.}
\end{table}


We followed a similar approach for SDO. 
We first averaged responses within pairs of
items that queried the same aspect of SDO using opposing polarity 
(items \textit{SDO1} and \textit{SDO4}; \textit{SDO2 }and \textit{SDO3}; \textit{SDO5} and \textit{SDO7}, and \textit{SDO6}
 and \textit{SDO8})
before using the resulting 4 averages as indicator variables.
For the remaining constructs, indicator variables were entered directly
into the measurement models.

All constructs were found to exhibit an essentially uni-dimensional
structure, although in most cases one 
correlation between the residuals of two items
had to be
added to the single-factor model to achieve a satisfactory fit. We also
eliminated item \textit{IQ\_GEN5} from the model for IQ heritability because
its loading on the common factor was small and fit improved 
substantially when the item was removed. Unlike in Study~1, however, it
was possible to create a single-dimensional measurement model for the
IQ heritability construct.

Table~\ref{tab:indicatormodels2} reports the fit statistics for the
6 measurement models. For the constructs that were also used
in Study~1 or previous research \cite{Lewandowsky13b}, 
the fit statistics were similar and the
correlated residuals involved the same items as before.
As in Study~1, these measurement
models were used to estimate $\omega$ for each 
latent variable's single indicator (see Table~S6).

\begin{sidewaystable} %tab:indicatormodels2
	\setstretch{2}
	\caption{Model fit indices associated with the
		measurement models for all uni-dimensional constructs in Study~2}
	\label{tab:indicatormodels2}
	%\centering
	\begin{tabular}{l rrrrrr l}
		\thickline
		\multicolumn{1}{c}{Construct}   & $\chi^2$ & $df$ & SRMR & CFI & RMSEA & \multicolumn{1}{c}{90\% CI} & \multicolumn{1}{c}{Correlated residuals} \\
		\hline
		
		Norms of science &  
		\Sexpr{round(as.numeric(norgof["chisq"]),2)} & 
		\Sexpr{round(as.numeric(norgof["df"]))} & 
		\Sexpr{round(as.numeric(norgof["srmr"]),3)} & 
		\Sexpr{round(as.numeric(norgof["cfi"]),3)} & 
		\Sexpr{round(as.numeric(norgof["rmsea"]),3)} &
		\Sexpr{round(as.numeric(norgof["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(norgof["rmsea.ci.upper"]),3)}  & 
		\multicolumn{1}{c}{---}    \\
		
		Conservatism & 
		\Sexpr{round(as.numeric(polgof["chisq"]),2)} & 
		\Sexpr{round(as.numeric(polgof["df"]))} & 
		\Sexpr{round(as.numeric(polgof["srmr"]),3)} & 
		\Sexpr{round(as.numeric(polgof["cfi"]),3)} & 
		\Sexpr{round(as.numeric(polgof["rmsea"]),3)} &
		\Sexpr{round(as.numeric(polgof["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(polgof["rmsea.ci.upper"]),3)}  & 
		\textit{POL\_CONS2} $\leftrightarrow$ \textit{POL\_CONS4}  \\
		
		IQ heritable & 
		\Sexpr{round(as.numeric(IQgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(IQgof2["df"]))} & 
		\Sexpr{round(as.numeric(IQgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(IQgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(IQgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(IQgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(IQgof2["rmsea.ci.upper"]),3)}  & 
		\textit{IQ\_GEN2} $\leftrightarrow$ \textit{IQ\_GEN2}  \\
		
		Climate science & 
		\Sexpr{round(as.numeric(climgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(climgof2["df"]))} & 
		\Sexpr{round(as.numeric(climgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(climgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(climgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(climgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(climgof2["rmsea.ci.upper"]),3)}  & 
		\textit{CNatFluct} $\leftrightarrow$ \textit{HumansInsign}  \\
		
		Vaccinations & 
		\Sexpr{round(as.numeric(vaxgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(vaxgof2["df"]))} & 
		\Sexpr{round(as.numeric(vaxgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(vaxgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(vaxgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(vaxgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(vaxgof2["rmsea.ci.upper"]),3)}  & 
		\textit{VaxNegSide} $\leftrightarrow$  \textit{VaxRisky} \\
		
		Social dominance orientation (SDO) & 
		\Sexpr{round(as.numeric(sdogof["chisq"]),2)} & 
		\Sexpr{round(as.numeric(sdogof["df"]))} & 
		\Sexpr{round(as.numeric(sdogof["srmr"]),3)} & 
		\Sexpr{round(as.numeric(sdogof["cfi"]),3)} & 
		\Sexpr{round(as.numeric(sdogof["rmsea"]),3)} &
		\Sexpr{round(as.numeric(sdogof["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(sdogof["rmsea.ci.upper"]),3)}  & 
		\textit{SDO1\&4} $\leftrightarrow$  \textit{SDO2\&3} \\
		\thickline
	\end{tabular}
\end{sidewaystable}



\subsubsection{Correlations among latent variables}

Table~\ref{tab:lvcor2} shows the correlation 
matrix for the 6 single-indicator latent variables. All correlations
were significant at $p<.0001$, except for 
the correlation between IQ heritable and norms of science, $p<.003$, and
a non-significant correlation between IQ Heritable and Vaccinations.

\begin{sidewaystable}[!htbp] \centering 
	\setstretch{2}
	\caption{Correlations among 6 unidimensional latent variables in Study~2} 
	\label{tab:lvcor2} 
	\begin{tabular}{@{\extracolsep{2pt}} l cccccc} 
		\\[-1.2ex]\hline 
		\hline \\[-1.8ex] 
		
		\input{_t.lvcor2.tex}
		
		\hline \\[-1.8ex] 
	\end{tabular} 
\end{sidewaystable}

\subsubsection{Predictive models}
We next identified individual predictive models for 
each of the three 
scientific constructs (IQ Heritable, Climate, and Vaccinations).
As in Study~1, we first fit a full model involving all 
potential predictor 
constructs (Norms of science, Conservatism, and SDO)
and then eliminated predictors until we found the simplest
possible model that did not incur a significant loss of fit. 
Table~\ref{tab:predmodelcomp2} summarizes those models.
Note that the model for climate science was fully
saturated and hence fit perfectly. Removal of any of the three
predictors was associated with highly significant loss of fit. 

\begin{sidewaystable} %tab:predmodelcomp2
	\setstretch{2}
	\caption{Model fit indices and predictors associated with the 
		simplest predictive model for each scientific construct in Study~2}
	\label{tab:predmodelcomp2}
	%\centering
	\begin{tabular}{l rrrrrr l}
		\thickline
		\multicolumn{1}{c}{Construct}   & $\chi^2$ & $df$ & SRMR & CFI & RMSEA & \multicolumn{1}{c}{90\% CI} & \multicolumn{1}{c}{Predictors} \\
		\hline
		IQ Heritable &
		\Sexpr{round(as.numeric(smIQgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(smIQgof2["df"]))} & 
		\Sexpr{round(as.numeric(smIQgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(smIQgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(smIQgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(smIQgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(smIQgof2["rmsea.ci.upper"]),3)}  & Norms; SDO \\
		
		Climate & 
		\Sexpr{round(as.numeric(smclimgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(smclimgof2["df"]))} & 
		\Sexpr{round(as.numeric(smclimgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(smclimgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(smclimgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(smclimgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(smclimgof2["rmsea.ci.upper"]),3)}  & Norms; SDO; Conservatism \\
		
		Vaccinations & 
		\Sexpr{round(as.numeric(smvaxgof2["chisq"]),2)} & 
		\Sexpr{round(as.numeric(smvaxgof2["df"]))} & 
		\Sexpr{round(as.numeric(smvaxgof2["srmr"]),3)} & 
		\Sexpr{round(as.numeric(smvaxgof2["cfi"]),3)} & 
		\Sexpr{round(as.numeric(smvaxgof2["rmsea"]),3)} &
		\Sexpr{round(as.numeric(smvaxgof2["rmsea.ci.lower"]),3)} -- 
		\Sexpr{round(as.numeric(smvaxgof2["rmsea.ci.upper"]),3)}  & Norms; SDO \\
		
		\thickline
	\end{tabular}
\end{sidewaystable}

Using the same approach as in Study~1, we selected the simplest
possible model to predict all scientific constructs.
This overall model is shown in Figure~\ref{fig:Exp2SEM}.
The model fit very well, $\chi^2(\Sexpr{fitallgof2["df"]})=\Sexpr{round(fitallgof2["chisq"],2)}$, $p = \Sexpr{round(fitallgof2["pvalue"],4)}$; 
SRMR=\Sexpr{round(fitallgof2["srmr"],3)}; CFI=\Sexpr{round(fitallgof2["cfi"],3)}; 
RMSEA=\Sexpr{round(fitallgof2["rmsea"],3)} (90\% CI:
\Sexpr{round(fitallgof2["rmsea.ci.lower"],3)}--
\Sexpr{round(fitallgof2["rmsea.ci.upper"],3)}).
The predictive model replicated Study~1 in several important ways. 
First, conservatism and the closely allied SDO construct
predicted rejection of climate science, as expected. 
Second, SDO predicted endorsement of the heritability of
intelligence, confirming the suggestion that any
hierarchical view of the world---whether at the level of nations or groups
within a society---finds its reflection in the expectation
of innate and presumably invariant differences in intelligence 
between individuals. 
The predictive model also highlighted a novel contribution of Study~2,
namely the findings that acceptance of the norms of science was
negatively associated with conservatism and SDO, and that it 
predicted endorsement of two scientific findings relating
to climate change and vaccinations (see also Table~\ref{tab:lvcor2}). 

\begin{figure}[tp] %fig:Exp2SEM
	\fitfigure{Exp2SEM.pdf}
	\caption{Final predictive structural equation model for Study~2. 
		All links and correlations shown are 
		standardized and significant; all $p < .002$. Negative values are highlighted by gray shading.
		Indicator variables and their loadings, and disturbances on endogenous 
		factors are not
		shown. Links between latent variables that are not shown are 
		not significant or constrained to zero.
		Loadings and variances of single-indicator latent 
		variables are reported in Tables~\ref{tab:indicatormodels2}
		and~S6.}
	\label{fig:Exp2SEM}
\end{figure}



\section{General Discussion}

\subsection{Worldviews and the heritability of intelligence}
We chose to probe people's attitudes about the sources of individual differences
in intelligence because
of the centrality of the belief in human improvement in liberal and
left-wing thought \cite{Porter13,Rattan12}.
Across both studies, our results provide little evidence
that this belief impairs people's recognition
that intelligence is, at least in part, heritable.
In Study~1, we found 
 no association between religiosity or free-market
attitudes, two powerful proxies for conservatism, and people's belief
that intelligence is shaped by the environment rather than genetics. 
In Study~2, the zero-order correlation between conservatism and heritability 
was positive and significant (implying that liberals were less likely to 
endorse heritability of intelligence) but when other variables
were controlled in the predictive model, this relationship disappeared.

Our results mesh well with a recent survey of sociologists, 
a discipline that has been cited as being  
particularly ``left-wing'' \cite{Winegard17}, which found
that more than 80\% of respondents endorsed a role of genetics in determining
people's intellectual potential \cite{Horowitz14}.
This clear endorsement of heritability among people seen as
predominantly ``left-wing'' is not compatible with the suspicion 
that this particular scientific evidence might be dismissed in favor of ideology among
people on the left.
The only hint in our data that people on the left might me more inclined to 
think that intelligence can be shaped by the environment arises
from the positive association between nationalism (Study~1) 
or SDO (Study~2) and heritability. Both nationalism and SDO are
less prevalent on the left than the political right, although
both only tap a subset of the liberal-conservatism spectrum.

Our findings thus add
to the catalogue
of unsuccessful attempts to find strong evidence for 
science denial on the political left in attitudinal
surveys. 
Although there has been some  media speculation
that people on the left are unreasonably skeptical of 
genetically-modified (GM) foods \cite{Kloor12W,Shermer13W} or vaccinations\cite{Mooney11W},
those speculations have failed to find much empirical support to date.
Although in a regional survey liberals appear to be more
wary of GM foods by supporting legislation
requiring labeling \cite{Hamilton14b}, they also trust scientists more on questions
relating to GM than conservatives \cite{Hamilton15c}.
In a nationally representative
survey in the U.S., neither conservatism nor free-market endorsement 
predicted attitudes towards
GM foods \cite<e.g.,>{Lewandowsky13b}. In another recent analysis of
U.S. responses to the International Social Survey Program, \citeA{Rutjens17}
found a small but significant effect of conservatism ($\beta = -.08$), indicating that conservatives
were \textit{less} sceptical of GM. Across three studies, \citeA{Rutjens17} nonetheless
conclude that ``GM
food skepticism is not driven by political or religious beliefs'' (p.~395).

Concerning vaccinations, 
\citeA{Hamilton15a} showed that
trust in scientists regarding vaccinations was
greater among Democrats than Republicans, 
and \citeA{Kahan10a} showed that conservatives' opposition to vaccination
was particularly acute 
in the context of sexually transmitted diseases such as
the human-papillomavirus (HPV) responsible for cervical
cancer. 
Similarly, free-market endorsement has repeatedly 
been shown to be a predictor of rejection of vaccinations 
(\citeNP{Lewandowsky13b,Lewandowsky20g}, and the present Study~1).
Intriguingly, when conservatism is considered separately
from free-market endorsement, it is not associated with
attitudes towards vaccinations (Model 2 in \citeNP{Lewandowsky13b}; \citeNP{Lewandowsky20g}, 
and the present Study~2, although the present measure of conservatism
included one free-market item).
The available data thus suggest that it is libertarianism, rather
than socio-political conservatism, 
that makes people reluctant to endorse vaccinations, perhaps because
the issue is overshadowed by potential government interference (e.g., by making
vaccinations mandatory). Either way, the conjecture that vaccinations
are primarily rejected by people on the political left finds no support
in the data (see also, \citeNP{Hornsey18}).

\subsection{Worldviews and the norms of science}
The broad range of results showing conservatives to be more likely 
to reject scientific findings than liberals motivated our question
whether there is anything 
about the scientific enterprise itself that may challenge people with
rightwing or libertarian worldviews.
We were particularly concerned with the universalist and communist 
norms of science \cite{Merton42}; namely, that science 
transcends racial, class, and national barriers and that its findings
belong to the community as a whole. Those norms stand in obvious
opposition to streams of conservative thought, and in support our first study
confirmed that nationalism was a predictor of the rejection of
well-established scientific findings relating to climate 
change and vaccinations. 

Our second study extended this
using a more direct and broader test of people's attitudes 
towards the norms of science. Endorsement of the norms of science
was a positive predictor of acceptance of climate science and 
vaccinations, and it was negatively associated with conservatism
and SDO. 

Taken together, the results of our two studies provide a potential
explanation for why conservatives 
are more likely to reject scientific findings than liberals. 
Previous accounts have focused on the ideologically asymmetrical
challenge posed by current scientifically-based problems \cite{Kahan15,Lewandowsky16b}.
On that account, conservatives reject climate science not because they
reject science \textit{per se} but because climate mitigation requires
changes to current economic practice. 

Our findings show that this view is, at best, incomplete. In addition to 
the obvious clash between conservative views 
and specific scientific results, we have identified 
a general tension between conservative thought and the norms of science
(bearing in mind the exception for skepticism; see Table~\ref{tab:normcors}).
The pervasive
rejection of science by people on the right observed here and in many
other studies is thus not just coincidental 
or dictated by political pragmatics, 
but also represents a deep
conflict between science and conservatism.

\subsection{Attitudinal asymmetry and potential cognitive symmetry}

The finding that science denial primarily---or indeed
exclusively---involves the political right
meshes well
with reports of greater gullibility and receptivity to false information
among people on the political
right. For example, \citeA{Sterling16} found that
individuals who endorsed a neoliberal, free market ideology were more
susceptible to what they called ``pseudo-profound bullshit;'' that is, 
vague or meaningless statements composed of intellectual lingo
such as ``consciousness is the growth of coherence, and of us.'' Similar findings
were reported by \citeA{Pfattheicher16}.
This asymmetrical theme is also revealed in
recent ``big-data'' analyses, which have 
reported evidence of substantial 
selective exposure to fake news, with Trump supporters
consuming more news from
untrustworthy websites than others \cite{Guess20a}. 
Similarly, a recent large-scale study of Twitter users has found 
that sharing of misinformation was disproportionately concentrated 
among older Republicans~\cite{Grinberg19}. 
Perhaps unsurprisingly, rejection of science, endorsement of pseudo-profound but
meaningless statements, and susceptibility to ``fake news'' 
may turn out to be diverse sides of the same political coin.

In striking contrast to those reports of asymmetry, laboratory 
experiments have repeatedly shown 
that the propensity to engage in cognitive shortcuts---that is,
responding on 
the basis of superficial association rather than deep reflection---is distributed
evenly across the political divide. 
When participants are presented with synthetic data (e.g., hypothetical
results of gun control laws) that are
amenable to a quick---but inaccurate---interpretation,
as well as to a competing complex---and accurate---interpretation, the
quick but inaccurate interpretation is triggered when 
it is worldview congruent, irrespective of the person's beliefs.
Conversely, the more complex and accurate
reading of the data is recruited only when the quick interpretation 
challenges participants' worldview, and this effect also holds
irrespective of a person's beliefs \cite{Kahan13a,Washburn17}. 
These data suggest that when people are asked to engage in
cognitive processing to interpret data in the laboratory, as opposed to 
expressing
their pre-existing attitudes in a survey, then conservatives and liberals
engage seemingly identical cognitive processes.
Similar nearly-symmetrical processing of corrections to misinformation
has been reported by \citeA{Swire20} with Trump voters and Sanders 
voters.\footnote{ There are, however, exceptions to this symmetry.
In some experimental studies, interventions
had different effects on people
with different worldviews. For example, \citeA{Tullett16}
found conservatives 
to be more likely to avoid seeking novel data in response
to an open-ended question (e.g., ``justness'' of the world)
than liberals.
Moreover, a recent
meta analysis has identified consistent cognitive differences
on a number of measures
between people on the political left and right \cite{Jost17}.
The list of measures is extensive and includes
assays of analytical reasoning such
as the cognitive reflection test \cite{Frederick05}. }

We are thus presented with a puzzle: if people across the political spectrum can
engage the same cognitive processes to interpret numeric data or process
corrections in the laboratory, how
can they differ so reliably and asymmetrically in their attitudes towards a 
broad range of scientific findings?
The present results suggest that the resolution of the puzzle 
may lie in the tension between the norms that govern the scientific enterprise and
conservative political thought. 
Conservatives are less likely to endorse the norms of science, 
and therefore are more inclined to distrust scientific results in general. 
This general propensity to distrust science is tapped in surveys that 
ask about a person's pre-existing view about scientific findings on a 
broad topic such as climate change or vaccinations. Those views, in turn,
have likely been formed over time based on information from the media, 
friends and family, community leaders, 
and other public sources that a person finds credible. On each of those occasions,
there is an opportunity to consider that testimony through the lens of
the norms of science. 
By contrast, in laboratory experiments where people are asked to 
draw their own conclusions from specific data, 
it appears that the propensity to distrust
science is not activated by the task at hand. 
This account is necessarily speculative but it gives
rise to several interesting empirical questions about the 
relationship between the two paradigms that can be explored
in future research, such as whether explicit reminders
about the norms of science would affect subsequent interpretation 
of the data, or conversely, whether partisan differences in
attitudes might become attenuated by prior processing of data.
 
\begin{thebibliography}{}
	
	\bibitem [\protect \citeauthoryear {%
		Allum%
		, Sturgis%
		, Tabourazi%
		\BCBL {}\ \BBA {} Brunton-Smith%
	}{%
		Allum%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2008}}%
	}]{%
		Allum08}
	\APACinsertmetastar {%
		Allum08}%
	\begin{APACrefauthors}%
		Allum, N.%
		, Sturgis, P.%
		, Tabourazi, D.%
		\BCBL {}\ \BBA {} Brunton-Smith, I.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2008}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Science knowledge and attitudes across cultures: a
		meta-analysis} {Science knowledge and attitudes across cultures: a
		meta-analysis}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Public Understanding of Science}{17}{}{35--54}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0963662506070159} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Au%
		\ \protect \BOthers {.}}{%
		Au%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Au15}
	\APACinsertmetastar {%
		Au15}%
	\begin{APACrefauthors}%
		Au, J.%
		, Sheehan, E.%
		, Tsai, N.%
		, Duncan, G\BPBI J.%
		, Buschkuehl, M.%
		\BCBL {}\ \BBA {} Jaeggi, S\BPBI M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Improving fluid intelligence with training on working
		memory: a meta-analysis} {Improving fluid intelligence with training on
		working memory: a meta-analysis}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychonomic Bulletin {\&} Review}{22}{}{366--377}.
	\newblock
	\begin{APACrefDOI} \doi{10.3758/s13423-014-0699-x} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Bentler%
		\ \BBA {} Chou%
	}{%
		Bentler%
		\ \BBA {} Chou%
	}{%
		{\protect \APACyear {1987}}%
	}]{%
		Bentler87}
	\APACinsertmetastar {%
		Bentler87}%
	\begin{APACrefauthors}%
		Bentler, P\BPBI M.%
		\BCBT {}\ \BBA {} Chou, C\BHBI P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1987}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Practical Issues in Structural Modeling} {Practical
		issues in structural modeling}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Sociological Methods \& Research}{16}{}{78--117}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Bogart%
		, Galvan%
		, Wagner%
		\BCBL {}\ \BBA {} Klein%
	}{%
		Bogart%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2011}}%
	}]{%
		Bogart11}
	\APACinsertmetastar {%
		Bogart11}%
	\begin{APACrefauthors}%
		Bogart, L\BPBI M.%
		, Galvan, F\BPBI H.%
		, Wagner, G\BPBI J.%
		\BCBL {}\ \BBA {} Klein, D\BPBI J.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2011}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Longitudinal Association of {HIV} Conspiracy Beliefs
		with Sexual Risk Among Black Males Living with {HIV}} {Longitudinal
		association of {HIV} conspiracy beliefs with sexual risk among black males
		living with {HIV}}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{AIDS and Behavior}{15}{}{1180--1186}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s10461-010-9796-7.} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Capstick%
		\ \BBA {} Pidgeon%
	}{%
		Capstick%
		\ \BBA {} Pidgeon%
	}{%
		{\protect \APACyear {2014}}%
	}]{%
		Capstick14}
	\APACinsertmetastar {%
		Capstick14}%
	\begin{APACrefauthors}%
		Capstick, S\BPBI B.%
		\BCBT {}\ \BBA {} Pidgeon, N\BPBI F.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {What is climate change scepticism? Examination of the
		concept using a mixed methods study of the {UK} public} {What is climate
		change scepticism? examination of the concept using a mixed methods study of
		the {UK} public}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Global Environmental Change}{24}{0}{389--401}.
	\newblock
	\begin{APACrefURL}
		\url{http://www.sciencedirect.com/science/article/pii/S0959378013001477}
	\end{APACrefURL}
	\newblock
	\begin{APACrefDOI} \doi{http://dx.doi.org/10.1016/j.gloenvcha.2013.08.012}
	\end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Castagno%
	}{%
		Castagno%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Castagno17}
	\APACinsertmetastar {%
		Castagno17}%
	\begin{APACrefauthors}%
		Castagno, A\BPBI E.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Liberal Ideologies and Federal School Reform: Following
		Individualism, Meliorism, and Neutrality Through {SIG} Policy to {A}delante
		{A}lternative {S}chool} {Liberal ideologies and federal school reform:
		Following individualism, meliorism, and neutrality through {SIG} policy to
		{A}delante {A}lternative {S}chool}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Urban Education}{}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0042085916685762} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Chigwedere%
		, Seage%
		, Gruskin%
		, Lee%
		\BCBL {}\ \BBA {} Essex%
	}{%
		Chigwedere%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2008}}%
	}]{%
		Chigwedere08}
	\APACinsertmetastar {%
		Chigwedere08}%
	\begin{APACrefauthors}%
		Chigwedere, P.%
		, Seage, I., G.~R.%
		, Gruskin, S.%
		, Lee, T\BHBI H.%
		\BCBL {}\ \BBA {} Essex, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2008}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Estimating the Lost Benefits of Antiretroviral Drug Use
		in {S}outh {A}frica} {Estimating the lost benefits of antiretroviral drug use
		in {S}outh {A}frica}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Acquired Immune Deficiency
		Syndrome}{49}{}{410--415}.
	\newblock
	\begin{APACrefDOI} \doi{10.1097/QAI.0b013e31818a6cd5} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Coffman%
		\ \BBA {} MacCallum%
	}{%
		Coffman%
		\ \BBA {} MacCallum%
	}{%
		{\protect \APACyear {2005}}%
	}]{%
		Coffman05}
	\APACinsertmetastar {%
		Coffman05}%
	\begin{APACrefauthors}%
		Coffman, D\BPBI L.%
		\BCBT {}\ \BBA {} MacCallum, R\BPBI C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2005}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Using Parcels to Convert Path Analysis Models Into
		Latent Variable Models} {Using parcels to convert path analysis models into
		latent variable models}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Multivariate Behavioral Research}{40}{}{235--259}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Cook%
		\ \BBA {} Lewandowsky%
	}{%
		Cook%
		\ \BBA {} Lewandowsky%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		Cook16}
	\APACinsertmetastar {%
		Cook16}%
	\begin{APACrefauthors}%
		Cook, J.%
		\BCBT {}\ \BBA {} Lewandowsky, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Rational Irrationality: {M}odeling Climate Change Belief
		Polarization Using {B}ayesian Networks} {Rational irrationality: {M}odeling
		climate change belief polarization using {B}ayesian networks}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Topics in Cognitive Science}{8}{}{160--179}.
	\newblock
	\begin{APACrefDOI} \doi{10.1111/tops.12186} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Devine-Wright%
		, Price%
		\BCBL {}\ \BBA {} Leviston%
	}{%
		Devine-Wright%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		DevineWright15}
	\APACinsertmetastar {%
		DevineWright15}%
	\begin{APACrefauthors}%
		Devine-Wright, P.%
		, Price, J.%
		\BCBL {}\ \BBA {} Leviston, Z.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {My country or my planet? {E}xploring the influence of
		multiple place attachments and ideological beliefs upon climate change
		attitudes and opinions} {My country or my planet? {E}xploring the influence
		of multiple place attachments and ideological beliefs upon climate change
		attitudes and opinions}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Global Environmental Change}{30}{}{68 - 79}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.gloenvcha.2014.10.012} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Dhont%
		\ \BBA {} Hodson%
	}{%
		Dhont%
		\ \BBA {} Hodson%
	}{%
		{\protect \APACyear {2014}}%
	}]{%
		Dhont14a}
	\APACinsertmetastar {%
		Dhont14a}%
	\begin{APACrefauthors}%
		Dhont, K.%
		\BCBT {}\ \BBA {} Hodson, G.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Why do right-wing adherents engage in more animal
		exploitation and meat consumption?} {Why do right-wing adherents engage in
		more animal exploitation and meat consumption?}{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Personality and Individual Differences}{64}{}{12--17}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.paid.2014.02.002} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Dhont%
		, Hodson%
		\BCBL {}\ \BBA {} Leite%
	}{%
		Dhont%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Dhont16}
	\APACinsertmetastar {%
		Dhont16}%
	\begin{APACrefauthors}%
		Dhont, K.%
		, Hodson, G.%
		\BCBL {}\ \BBA {} Leite, A\BPBI C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Common {Ideological} {Roots} of {Speciesism} and
		{Generalized} {Ethnic} {Prejudice}: {The} {Social} {Dominance}
		{Human}–{Animal} {Relations} {Model} ({SD}-{HARM})} {Common {Ideological}
		{Roots} of {Speciesism} and {Generalized} {Ethnic} {Prejudice}: {The}
		{Social} {Dominance} {Human}–{Animal} {Relations} {Model}
		({SD}-{HARM})}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{European Journal of Personality}{30}{}{507--522}.
	\newblock
	\begin{APACrefDOI} \doi{https://doi.org/10.1002/per.2069} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Dougherty%
		, Hamovitz%
		\BCBL {}\ \BBA {} Tidwell%
	}{%
		Dougherty%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Dougherty16}
	\APACinsertmetastar {%
		Dougherty16}%
	\begin{APACrefauthors}%
		Dougherty, M\BPBI R.%
		, Hamovitz, T.%
		\BCBL {}\ \BBA {} Tidwell, J\BPBI W.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Reevaluating the effectiveness of n-back training on
		transfer through the Bayesian lens: Support for the null} {Reevaluating the
		effectiveness of n-back training on transfer through the bayesian lens:
		Support for the null}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychonomic Bulletin {\&} Review}{23}{}{306--316}.
	\newblock
	\begin{APACrefDOI} \doi{10.3758/s13423-015-0865-9} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Dunlap%
		, Van~Liere%
		, Mertig%
		\BCBL {}\ \BBA {} Jones%
	}{%
		Dunlap%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2000}}%
	}]{%
		Dunlap00}
	\APACinsertmetastar {%
		Dunlap00}%
	\begin{APACrefauthors}%
		Dunlap, R\BPBI E.%
		, Van~Liere, K\BPBI D.%
		, Mertig, A\BPBI G.%
		\BCBL {}\ \BBA {} Jones, R\BPBI E.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2000}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Measuring Endorsement of the New Ecological Paradigm:
		{A} Revised {NEP} Scale} {Measuring endorsement of the new ecological
		paradigm: {A} revised {NEP} scale}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Social Issues}{56}{}{425--442}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Dweck%
		, Chiu%
		\BCBL {}\ \BBA {} Hong%
	}{%
		Dweck%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {1995}}%
	}]{%
		Dweck95}
	\APACinsertmetastar {%
		Dweck95}%
	\begin{APACrefauthors}%
		Dweck, C\BPBI S.%
		, Chiu, C\BHBI y.%
		\BCBL {}\ \BBA {} Hong, Y\BHBI y.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1995}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Implicit theories and their role in judgments and
		reactions: A word from two perspectives} {Implicit theories and their role in
		judgments and reactions: A word from two perspectives}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological inquiry}{6}{}{267--285}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Ecklund%
		, Scheitle%
		, Peifer%
		\BCBL {}\ \BBA {} Bolger%
	}{%
		Ecklund%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2017}}%
	}]{%
		Ecklund17}
	\APACinsertmetastar {%
		Ecklund17}%
	\begin{APACrefauthors}%
		Ecklund, E\BPBI H.%
		, Scheitle, C\BPBI P.%
		, Peifer, J.%
		\BCBL {}\ \BBA {} Bolger, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Examining Links Between Religion, Evolution Views, and
		Climate Change Skepticism} {Examining links between religion, evolution
		views, and climate change skepticism}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Environment and Behavior}{49}{}{985--1006}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0013916516674246} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Everett%
	}{%
		Everett%
	}{%
		{\protect \APACyear {2013}}%
	}]{%
		Everett13}
	\APACinsertmetastar {%
		Everett13}%
	\begin{APACrefauthors}%
		Everett, J\BPBI A.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The 12 Item Social and Economic Conservatism Scale
		{(SECS)}} {The 12 item social and economic conservatism scale
		{(SECS)}}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLOS ONE}{8}{}{e82131}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pone.0082131} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Finlay%
		\ \BBA {} Workman%
	}{%
		Finlay%
		\ \BBA {} Workman%
	}{%
		{\protect \APACyear {2013}}%
	}]{%
		Finlay13}
	\APACinsertmetastar {%
		Finlay13}%
	\begin{APACrefauthors}%
		Finlay, B\BPBI L.%
		\BCBT {}\ \BBA {} Workman, A\BPBI D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Human exceptionalism} {Human exceptionalism}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Trends in Cognitive Sciences}{17}{}{199 -- 201}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.tics.2013.03.001} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Frederick%
	}{%
		Frederick%
	}{%
		{\protect \APACyear {2005}}%
	}]{%
		Frederick05}
	\APACinsertmetastar {%
		Frederick05}%
	\begin{APACrefauthors}%
		Frederick, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2005}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Cognitive Reflection and Decision Making} {Cognitive
		reflection and decision making}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{The Journal of Economic Perspectives}{19}{}{25--42}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Gangarosa%
		\ \protect \BOthers {.}}{%
		Gangarosa%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {1998}}%
	}]{%
		Gangarosa98}
	\APACinsertmetastar {%
		Gangarosa98}%
	\begin{APACrefauthors}%
		Gangarosa, E\BPBI J.%
		, Galazka, A\BPBI M.%
		, Wolfe, C\BPBI R.%
		, Phillips, L\BPBI M.%
		, Gangarosa, R\BPBI E.%
		, Miller, E.%
		\BCBL {}\ \BBA {} Chen, R\BPBI T.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1998}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Impact of anti-vaccine movements on pertussis control:
		the untold story} {Impact of anti-vaccine movements on pertussis control: the
		untold story}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Lancet}{351}{}{356--361}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/S0140-6736(97)04334-1} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Gauchat%
	}{%
		Gauchat%
	}{%
		{\protect \APACyear {2012}}%
	}]{%
		Gauchat12}
	\APACinsertmetastar {%
		Gauchat12}%
	\begin{APACrefauthors}%
		Gauchat, G.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Politicization of Science in the Public Sphere: {A}
		Study of Public Trust in the {U}nited {S}tates, 1974 to 2010} {Politicization
		of science in the public sphere: {A} study of public trust in the {U}nited
		{S}tates, 1974 to 2010}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{American Sociological Review}{77}{}{167--187}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Gottlieb%
		\ \BBA {} Lombrozo%
	}{%
		Gottlieb%
		\ \BBA {} Lombrozo%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Gottlieb17}
	\APACinsertmetastar {%
		Gottlieb17}%
	\begin{APACrefauthors}%
		Gottlieb, S.%
		\BCBT {}\ \BBA {} Lombrozo, T.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Can Science Explain the Human Mind? {I}ntuitive
		Judgments About the Limits of Science} {Can science explain the human mind?
		{I}ntuitive judgments about the limits of science}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological Science}{}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0956797617722609} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Grinberg%
		, Joseph%
		, Friedland%
		, Swire-Thompson%
		\BCBL {}\ \BBA {} Lazer%
	}{%
		Grinberg%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2019}}%
	}]{%
		Grinberg19}
	\APACinsertmetastar {%
		Grinberg19}%
	\begin{APACrefauthors}%
		Grinberg, N.%
		, Joseph, K.%
		, Friedland, L.%
		, Swire-Thompson, B.%
		\BCBL {}\ \BBA {} Lazer, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2019}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Fake news on {T}witter during the 2016 {U.S}.
		presidential election} {Fake news on {T}witter during the 2016 {U.S}.
		presidential election}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Science}{363}{}{374--378}.
	\newblock
	\begin{APACrefDOI} \doi{10.1126/science.aau2706} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Guess%
		, Nyhan%
		\BCBL {}\ \BBA {} Reifler%
	}{%
		Guess%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2020}}%
	}]{%
		Guess20a}
	\APACinsertmetastar {%
		Guess20a}%
	\begin{APACrefauthors}%
		Guess, A\BPBI M.%
		, Nyhan, B.%
		\BCBL {}\ \BBA {} Reifler, J.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2020}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Exposure to untrustworthy websites in the 2016 {U.S.}
		election} {Exposure to untrustworthy websites in the 2016 {U.S.}
		election}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Nature Human Behavior}{in press}{}{}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hamilton%
	}{%
		Hamilton%
	}{%
		{\protect \APACyear {2011}}%
	}]{%
		Hamilton11}
	\APACinsertmetastar {%
		Hamilton11}%
	\begin{APACrefauthors}%
		Hamilton, L\BPBI C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2011}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Education, politics and opinions about climate change
		evidence for interaction effects} {Education, politics and opinions about
		climate change evidence for interaction effects}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Climatic Change}{104}{}{231--242}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s10584-010-9957-8} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hamilton%
	}{%
		Hamilton%
	}{%
		{\protect \APACyear {2014}}%
	}]{%
		Hamilton14b}
	\APACinsertmetastar {%
		Hamilton14b}%
	\begin{APACrefauthors}%
		Hamilton, L\BPBI C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	\APACrefbtitle {Do You Trust Scientists About the Environment? {N}ews Media
		Sources and Politics Affect {N}ew {H}ampshire Resident Views} {Do you trust
		scientists about the environment? {N}ews media sources and politics affect
		{N}ew {H}ampshire resident views}\ \APACbVolEdTR {}{Regional issue brief\
		\BNUM~40}.
	\newblock
	\APACaddressInstitution{}{University of New Hampshire}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hamilton%
	}{%
		Hamilton%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Hamilton15c}
	\APACinsertmetastar {%
		Hamilton15c}%
	\begin{APACrefauthors}%
		Hamilton, L\BPBI C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	\APACrefbtitle {Conservative and Liberal Views of Science: Does Trust Depend on
		Topic?} {Conservative and liberal views of science: Does trust depend on
		topic?}\ \APACbVolEdTR {}{Regional issue brief\ \BNUM~45}.
	\newblock
	\APACaddressInstitution{}{University of New Hampshire}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hamilton%
		, Hartter%
		, Lemcke-Stampone%
		, Moore%
		\BCBL {}\ \BBA {} Safford%
	}{%
		Hamilton%
		, Hartter%
		, Lemcke-Stampone%
		\BCBL {}\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Hamilton15b}
	\APACinsertmetastar {%
		Hamilton15b}%
	\begin{APACrefauthors}%
		Hamilton, L\BPBI C.%
		, Hartter, J.%
		, Lemcke-Stampone, M.%
		, Moore, D\BPBI W.%
		\BCBL {}\ \BBA {} Safford, T\BPBI G.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Tracking Public Beliefs About Anthropogenic Climate
		Change} {Tracking public beliefs about anthropogenic climate change}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLOS ONE}{10}{}{e0138208}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pone.0138208} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hamilton%
		, Hartter%
		\BCBL {}\ \BBA {} Saito%
	}{%
		Hamilton%
		, Hartter%
		\BCBL {}\ \BBA {} Saito%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Hamilton15a}
	\APACinsertmetastar {%
		Hamilton15a}%
	\begin{APACrefauthors}%
		Hamilton, L\BPBI C.%
		, Hartter, J.%
		\BCBL {}\ \BBA {} Saito, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Trust in Scientists on Climate Change and Vaccines}
	{Trust in scientists on climate change and vaccines}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{{SAGE} {O}pen}{5}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/2158244015602752} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hayduk%
	}{%
		Hayduk%
	}{%
		{\protect \APACyear {1996}}%
	}]{%
		Hayduk96}
	\APACinsertmetastar {%
		Hayduk96}%
	\begin{APACrefauthors}%
		Hayduk, L.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYear{1996}.
	\newblock
	\APACrefbtitle {{LISREL} issues, debates, and strategies} {{LISREL} issues,
		debates, and strategies}.
	\newblock
	\APACaddressPublisher{Baltimore, MD}{Johns Hopkins University.}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hill%
		\ \protect \BOthers {.}}{%
		Hill%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2018}}%
	}]{%
		Hill18}
	\APACinsertmetastar {%
		Hill18}%
	\begin{APACrefauthors}%
		Hill, W\BPBI D.%
		, Arslan, R\BPBI C.%
		, Xia, C.%
		, Luciano, M.%
		, Amador, C.%
		, Navarro, P.%
		\BDBL {}others%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Genomic analysis of family data reveals additional
		genetic effects on intelligence and personality} {Genomic analysis of family
		data reveals additional genetic effects on intelligence and
		personality}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Molecular psychiatry}{}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1038/s41380-017-0005-1} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Ho%
		\ \protect \BOthers {.}}{%
		Ho%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Ho15}
	\APACinsertmetastar {%
		Ho15}%
	\begin{APACrefauthors}%
		Ho, A\BPBI K.%
		, Sidanius, J.%
		, Kteily, N.%
		, Sheehy-Skeffington, J.%
		, Pratto, F.%
		, Henkel, K\BPBI E.%
		\BDBL {}Stewart, A\BPBI L.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The nature of social dominance orientation: Theorizing
		and measuring preferences for intergroup inequality using the new {SDO}
		scale} {The nature of social dominance orientation: Theorizing and measuring
		preferences for intergroup inequality using the new {SDO} scale}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Personality and Social
		Psychology}{109}{}{1003--1028}.
	\newblock
	\begin{APACrefDOI} \doi{10.1037/pspi0000033} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hornsey%
		, Harris%
		\BCBL {}\ \BBA {} Fielding%
	}{%
		Hornsey%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2018}}%
	}]{%
		Hornsey18}
	\APACinsertmetastar {%
		Hornsey18}%
	\begin{APACrefauthors}%
		Hornsey, M\BPBI J.%
		, Harris, E.%
		\BCBL {}\ \BBA {} Fielding, K\BPBI S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The psychological roots of anti-vaccination attitudes: A
		24-nation investigation} {The psychological roots of anti-vaccination
		attitudes: A 24-nation investigation}.{\BBCQ}
	\newblock
	
	\newblock
	\begin{APACrefDOI} \doi{10.1037/hea0000586} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hornsey%
		, Harris%
		, Bain%
		\BCBL {}\ \BBA {} Fielding%
	}{%
		Hornsey%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Hornsey16}
	\APACinsertmetastar {%
		Hornsey16}%
	\begin{APACrefauthors}%
		Hornsey, M\BPBI J.%
		, Harris, E\BPBI A.%
		, Bain, P\BPBI G.%
		\BCBL {}\ \BBA {} Fielding, K\BPBI S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Meta-analyses of the determinants and outcomes of belief
		in climate change} {Meta-analyses of the determinants and outcomes of belief
		in climate change}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Nature Climate Change}{}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1038/nclimate2943} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Horowitz%
		, Yaworsky%
		\BCBL {}\ \BBA {} Kickham%
	}{%
		Horowitz%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2014}}%
	}]{%
		Horowitz14}
	\APACinsertmetastar {%
		Horowitz14}%
	\begin{APACrefauthors}%
		Horowitz, M.%
		, Yaworsky, W.%
		\BCBL {}\ \BBA {} Kickham, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Whither the Blank Slate? {A} Report on the Reception of
		Evolutionary Biological Ideas among Sociological Theorists} {Whither the
		blank slate? {A} report on the reception of evolutionary biological ideas
		among sociological theorists}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Sociological Spectrum}{34}{}{489-509}.
	\newblock
	\begin{APACrefDOI} \doi{10.1080/02732173.2014.947451} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Hu%
		\ \BBA {} Bentler%
	}{%
		Hu%
		\ \BBA {} Bentler%
	}{%
		{\protect \APACyear {1999}}%
	}]{%
		Hu99}
	\APACinsertmetastar {%
		Hu99}%
	\begin{APACrefauthors}%
		Hu, L\BHBI t.%
		\BCBT {}\ \BBA {} Bentler, P\BPBI M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1999}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Cutoff Criteria for Fit Indexes in Covariance Structure
		Analysis: Conventional Criteria Versus New Alternatives} {Cutoff criteria for
		fit indexes in covariance structure analysis: Conventional criteria versus
		new alternatives}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Structural Equation Modeling}{6}{}{1--55}.
	\newblock
	\begin{APACrefDOI} \doi{10.1080/10705519909540118} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Jelen%
		\ \BBA {} Lockett%
	}{%
		Jelen%
		\ \BBA {} Lockett%
	}{%
		{\protect \APACyear {2014}}%
	}]{%
		Jelen14}
	\APACinsertmetastar {%
		Jelen14}%
	\begin{APACrefauthors}%
		Jelen, T\BPBI G.%
		\BCBT {}\ \BBA {} Lockett, L\BPBI A.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Religion, Partisanship, and Attitudes Toward Science
		Policy} {Religion, partisanship, and attitudes toward science policy}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{SAGE Open}{4}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/2158244013518932} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		J\"{o}reskog%
		\ \BBA {} S\"{o}rbom%
	}{%
		J\"{o}reskog%
		\ \BBA {} S\"{o}rbom%
	}{%
		{\protect \APACyear {1982}}%
	}]{%
		Joreskog82}
	\APACinsertmetastar {%
		Joreskog82}%
	\begin{APACrefauthors}%
		J\"{o}reskog, K\BPBI G.%
		\BCBT {}\ \BBA {} S\"{o}rbom, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1982}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Recent developments in structural equation modeling}
	{Recent developments in structural equation modeling}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Marketing Research}{19}{}{404--416}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Jost%
	}{%
		Jost%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Jost17}
	\APACinsertmetastar {%
		Jost17}%
	\begin{APACrefauthors}%
		Jost, J\BPBI T.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Ideological Asymmetries and the Essence of Political
		Psychology} {Ideological asymmetries and the essence of political
		psychology}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Political Psychology}{38}{}{167--208}.
	\newblock
	\begin{APACrefDOI} \doi{10.1111/pops.12407} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Jylhä%
		\ \BBA {} Akrami%
	}{%
		Jylhä%
		\ \BBA {} Akrami%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Jylha15}
	\APACinsertmetastar {%
		Jylha15}%
	\begin{APACrefauthors}%
		Jylhä, K\BPBI M.%
		\BCBT {}\ \BBA {} Akrami, N.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Social dominance orientation and climate change denial:
		{The} role of dominance and system justification} {Social dominance
		orientation and climate change denial: {The} role of dominance and system
		justification}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Personality and Individual
		Differences}{86}{}{108--111}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.paid.2015.05.041} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Jylh\"{a}%
		, Cantal%
		, Akrami%
		\BCBL {}\ \BBA {} Milfont%
	}{%
		Jylh\"{a}%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Jylha16}
	\APACinsertmetastar {%
		Jylha16}%
	\begin{APACrefauthors}%
		Jylh\"{a}, K\BPBI M.%
		, Cantal, C.%
		, Akrami, N.%
		\BCBL {}\ \BBA {} Milfont, T\BPBI L.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Denial of anthropogenic climate change: Social dominance
		orientation helps explain the conservative male effect in Brazil and Sweden}
	{Denial of anthropogenic climate change: Social dominance orientation helps
		explain the conservative male effect in brazil and sweden}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Personality and Individual Differences}{98}{}{184 --
		187}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.paid.2016.04.020} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kahan%
	}{%
		Kahan%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Kahan15}
	\APACinsertmetastar {%
		Kahan15}%
	\begin{APACrefauthors}%
		Kahan, D\BPBI M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Climate-Science Communication and the Measurement
		Problem} {Climate-science communication and the measurement problem}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Political Psychology}{36}{}{1--43}.
	\newblock
	\begin{APACrefDOI} \doi{10.1111/pops.12244} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kahan%
		, Braman%
		, Cohen%
		, Gastil%
		\BCBL {}\ \BBA {} Slovic%
	}{%
		Kahan%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2010}}%
	}]{%
		Kahan10a}
	\APACinsertmetastar {%
		Kahan10a}%
	\begin{APACrefauthors}%
		Kahan, D\BPBI M.%
		, Braman, D.%
		, Cohen, G\BPBI L.%
		, Gastil, J.%
		\BCBL {}\ \BBA {} Slovic, P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2010}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Who Fears the {HPV} Vaccine, Who Doesn’t, and Why?
		{A}n Experimental Study of the Mechanisms of Cultural Cognition} {Who fears
		the {HPV} vaccine, who doesn’t, and why? {A}n experimental study of the
		mechanisms of cultural cognition}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Law and Human Behavior}{34}{}{501--516}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kahan%
		, Peters%
		, Dawson%
		\BCBL {}\ \BBA {} Slovic%
	}{%
		Kahan%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2013}}%
	}]{%
		Kahan13a}
	\APACinsertmetastar {%
		Kahan13a}%
	\begin{APACrefauthors}%
		Kahan, D\BPBI M.%
		, Peters, E.%
		, Dawson, E\BPBI C.%
		\BCBL {}\ \BBA {} Slovic, P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	\APACrefbtitle {Motivated numeracy and enlightened self-government} {Motivated
		numeracy and enlightened self-government}\ \APACbVolEdTR{}{\BTR{}\
		\BNUM~307}.
	\newblock
	\APACaddressInstitution{}{Yale University Law School, Public Law Working
		Paper}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kahan%
		\ \protect \BOthers {.}}{%
		Kahan%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2012}}%
	}]{%
		Kahan12}
	\APACinsertmetastar {%
		Kahan12}%
	\begin{APACrefauthors}%
		Kahan, D\BPBI M.%
		, Peters, E.%
		, Wittlin, M.%
		, Slovic, P.%
		, Ouellette, L\BPBI L.%
		, Braman, D.%
		\BCBL {}\ \BBA {} Mandel, G.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The polarizing impact of science literacy and numeracy
		on perceived climate change risks} {The polarizing impact of science literacy
		and numeracy on perceived climate change risks}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Nature Climate Change}{2}{}{732--735}.
	\newblock
	\begin{APACrefDOI} \doi{10.1038/NCLIMATE1547} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Karbach%
		\ \BBA {} Verhaeghen%
	}{%
		Karbach%
		\ \BBA {} Verhaeghen%
	}{%
		{\protect \APACyear {2014}}%
	}]{%
		Karbach14}
	\APACinsertmetastar {%
		Karbach14}%
	\begin{APACrefauthors}%
		Karbach, J.%
		\BCBT {}\ \BBA {} Verhaeghen, P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Making Working Memory Work: A Meta-Analysis of
		Executive-Control and Working Memory Training in Older Adults} {Making
		working memory work: A meta-analysis of executive-control and working memory
		training in older adults}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological Science}{25}{}{2027-2037}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0956797614548725} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Karg%
		, Schmelz%
		, Call%
		\BCBL {}\ \BBA {} Tomasello%
	}{%
		Karg%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Karg15}
	\APACinsertmetastar {%
		Karg15}%
	\begin{APACrefauthors}%
		Karg, K.%
		, Schmelz, M.%
		, Call, J.%
		\BCBL {}\ \BBA {} Tomasello, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The goggles experiment: can chimpanzees use
		self-experience to infer what a competitor can see?} {The goggles experiment:
		can chimpanzees use self-experience to infer what a competitor can
		see?}{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Animal Behaviour}{105}{}{211 -- 221}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.anbehav.2015.04.028} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kenny%
	}{%
		Kenny%
	}{%
		{\protect \APACyear {2020}}%
	}]{%
		Kenny20}
	\APACinsertmetastar {%
		Kenny20}%
	\begin{APACrefauthors}%
		Kenny, D\BPBI A.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2020}{}{}.
	\newblock
	\APACrefbtitle {Measuring model fit.} {Measuring model fit.}
	\newblock
	\begin{APACrefURL} \url{http://www.davidakenny.net/cm/fit.htm} \end{APACrefURL}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Keshet%
	}{%
		Keshet%
	}{%
		{\protect \APACyear {2009}}%
	}]{%
		Keshet09}
	\APACinsertmetastar {%
		Keshet09}%
	\begin{APACrefauthors}%
		Keshet, Y.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2009}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The untenable boundaries of biomedical knowledge:
		epistemologies and rhetoric strategies in the debate over evaluating
		complementary and alternative medicine} {The untenable boundaries of
		biomedical knowledge: epistemologies and rhetoric strategies in the debate
		over evaluating complementary and alternative medicine}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Health: An Interdisciplinary Journal for the Social
		Study of Health, Illness and Medicine}{13}{}{131--155}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/1363459308099681} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kloor%
	}{%
		Kloor%
	}{%
		{\protect \APACyear {2012}}%
	}]{%
		Kloor12W}
	\APACinsertmetastar {%
		Kloor12W}%
	\begin{APACrefauthors}%
		Kloor, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{September}{}.
	\newblock
	\APACrefbtitle {{GMO} Opponents Are the Climate Skeptics of the Left
		(http://www.slate.com/articles/health\_and\_science/science/2012/09/\\are\_gmo\_foods\_safe\_opponents\_are\_skewing\_the\_science\_to\_scare\_people\_.html).}
	{{GMO} opponents are the climate skeptics of the left
		(http://www.slate.com/articles/health\_and\_science/science/2012/09/\\are\_gmo\_foods\_safe\_opponents\_are\_skewing\_the\_science\_to\_scare\_people\_.html).}
	\newblock
	\begin{APACrefURL}
		\url{http://www.slate.com/articles/health\_and\_science/science/2012/09/\\are\_gmo\_foods\_safe\_opponents\_are\_skewing\_the\_science\_to\_scare\_people\_.html}
	\end{APACrefURL}
	\newblock
	\APACrefnote{Accessed 29 September 2012}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Knutti%
		\ \BBA {} Rogelj%
	}{%
		Knutti%
		\ \BBA {} Rogelj%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Knutti15}
	\APACinsertmetastar {%
		Knutti15}%
	\begin{APACrefauthors}%
		Knutti, R.%
		\BCBT {}\ \BBA {} Rogelj, J.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The legacy of our {CO}\ensuremath{_2} emissions: a clash
		of scientific facts, politics and ethics} {The legacy of our
		{CO}\ensuremath{_2} emissions: a clash of scientific facts, politics and
		ethics}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Climatic Change}{133}{}{361-373}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s10584-015-1340-3} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Kosterman%
		\ \BBA {} Feshbach%
	}{%
		Kosterman%
		\ \BBA {} Feshbach%
	}{%
		{\protect \APACyear {1989}}%
	}]{%
		Kosterman89}
	\APACinsertmetastar {%
		Kosterman89}%
	\begin{APACrefauthors}%
		Kosterman, R.%
		\BCBT {}\ \BBA {} Feshbach, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1989}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Toward a Measure of Patriotic and Nationalistic
		Attitudes} {Toward a measure of patriotic and nationalistic
		attitudes}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Political Psychology}{10}{}{257--274}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Krange%
		, Kaltenborn%
		\BCBL {}\ \BBA {} Hultman%
	}{%
		Krange%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2018}}%
	}]{%
		Krange18}
	\APACinsertmetastar {%
		Krange18}%
	\begin{APACrefauthors}%
		Krange, O.%
		, Kaltenborn, B\BPBI P.%
		\BCBL {}\ \BBA {} Hultman, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Cool dudes in {N}orway: climate change denial among
		conservative {N}orwegian men} {Cool dudes in {N}orway: climate change denial
		among conservative {N}orwegian men}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Environmental Sociology}{}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1080/23251042.2018.1488516} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Laderman%
	}{%
		Laderman%
	}{%
		{\protect \APACyear {2018}}%
	}]{%
		Laderman18}
	\APACinsertmetastar {%
		Laderman18}%
	\begin{APACrefauthors}%
		Laderman, C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Conservative Internationalism: An Overview}
	{Conservative internationalism: An overview}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Orbis}{62}{}{6 -- 21}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.orbis.2017.11.009} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Landrum%
		, Olshansky%
		\BCBL {}\ \BBA {} Richards%
	}{%
		Landrum%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2019}}%
	}]{%
		Landrum19}
	\APACinsertmetastar {%
		Landrum19}%
	\begin{APACrefauthors}%
		Landrum, A\BPBI R.%
		, Olshansky, A.%
		\BCBL {}\ \BBA {} Richards, O.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2019}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Differential susceptibility to misleading flat earth
		arguments on {Y}ou{T}ube} {Differential susceptibility to misleading flat
		earth arguments on {Y}ou{T}ube}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Media Psychology}{}{}{1--30}.
	\newblock
	\begin{APACrefDOI} \doi{10.1080/15213269.2019.1669461} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Lewandowsky%
	}{%
		Lewandowsky%
	}{%
		{\protect \APACyear {2021}}%
		{\protect \APACexlab {{\protect \BCnt {1}}}}}]{%
		Lewandowsky21}
	\APACinsertmetastar {%
		Lewandowsky21}%
	\begin{APACrefauthors}%
		Lewandowsky, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2021{\protect \BCnt {1}}}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Climate change, disinformation, and how to combat it}
	{Climate change, disinformation, and how to combat it}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Annual Review of Public Health}{42}{}{1--21}.
	\newblock
	\begin{APACrefDOI} \doi{10.1146/annurev-publhealth-090419-102409}
	\end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Lewandowsky%
	}{%
		Lewandowsky%
	}{%
		{\protect \APACyear {2021}}%
		{\protect \APACexlab {{\protect \BCnt {2}}}}}]{%
		Lewandowsky21c}
	\APACinsertmetastar {%
		Lewandowsky21c}%
	\begin{APACrefauthors}%
		Lewandowsky, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2021{\protect \BCnt {2}}}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Conspiracist cognition: chaos, convenience, and cause
		for concern} {Conspiracist cognition: chaos, convenience, and cause for
		concern}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal for Cultural Research}{}{}{1--24}.
	\newblock
	\begin{APACrefDOI} \doi{10.1080/14797585.2021.1886423} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Lewandowsky%
		, Gignac%
		\BCBL {}\ \BBA {} Oberauer%
	}{%
		Lewandowsky%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2013}}%
	}]{%
		Lewandowsky13b}
	\APACinsertmetastar {%
		Lewandowsky13b}%
	\begin{APACrefauthors}%
		Lewandowsky, S.%
		, Gignac, G\BPBI E.%
		\BCBL {}\ \BBA {} Oberauer, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The Role of Conspiracist Ideation and Worldviews in
		Predicting Rejection of Science} {The role of conspiracist ideation and
		worldviews in predicting rejection of science}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLOS ONE}{8}{}{e75637}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pone.0075637} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Lewandowsky%
		\ \BBA {} Oberauer%
	}{%
		Lewandowsky%
		\ \BBA {} Oberauer%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		Lewandowsky16b}
	\APACinsertmetastar {%
		Lewandowsky16b}%
	\begin{APACrefauthors}%
		Lewandowsky, S.%
		\BCBT {}\ \BBA {} Oberauer, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Motivated rejection of science} {Motivated rejection of
		science}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Current Directions in Psychological
		Science}{25}{}{217--222}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0963721416654436} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Lewandowsky%
		, Woike%
		\BCBL {}\ \BBA {} Oberauer%
	}{%
		Lewandowsky%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2020}}%
	}]{%
		Lewandowsky20g}
	\APACinsertmetastar {%
		Lewandowsky20g}%
	\begin{APACrefauthors}%
		Lewandowsky, S.%
		, Woike, J\BPBI K.%
		\BCBL {}\ \BBA {} Oberauer, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2020}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Genesis or Evolution of Gender Differences?
		{W}orldview-Based Dilemmas in The Processing of Scientific Information}
	{Genesis or evolution of gender differences? {W}orldview-based dilemmas in
		the processing of scientific information}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Cognition}{3}{}{9}.
	\newblock
	\begin{APACrefDOI} \doi{10.5334/joc.99} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Li%
		, Hilgard%
		, Scheufele%
		, Winneg%
		\BCBL {}\ \BBA {} Jamieson%
	}{%
		Li%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Li16a}
	\APACinsertmetastar {%
		Li16a}%
	\begin{APACrefauthors}%
		Li, N.%
		, Hilgard, J.%
		, Scheufele, D\BPBI A.%
		, Winneg, K\BPBI M.%
		\BCBL {}\ \BBA {} Jamieson, K\BPBI H.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Cross-pressuring conservative {C}atholics? {E}ffects of
		{P}ope {F}rancis' encyclical on the {U.S.} public opinion on climate change}
	{Cross-pressuring conservative {C}atholics? {E}ffects of {P}ope {F}rancis'
		encyclical on the {U.S.} public opinion on climate change}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Climatic Change}{139}{}{367--380}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s10584-016-1821-z} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Little%
		, Cunningham%
		, Shahar%
		\BCBL {}\ \BBA {} Widaman%
	}{%
		Little%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2002}}%
	}]{%
		Little02}
	\APACinsertmetastar {%
		Little02}%
	\begin{APACrefauthors}%
		Little, T\BPBI D.%
		, Cunningham, W\BPBI A.%
		, Shahar, G.%
		\BCBL {}\ \BBA {} Widaman, K\BPBI F.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2002}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {To parcel or not to parcel: {E}xploring the question,
		weighing the merits} {To parcel or not to parcel: {E}xploring the question,
		weighing the merits}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Structural Equation Modeling}{9}{}{151--173}.
	\newblock
	\begin{APACrefDOI} \doi{10.1207/S15328007SEM0902_1} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Macfarlane%
		\ \BBA {} Cheng%
	}{%
		Macfarlane%
		\ \BBA {} Cheng%
	}{%
		{\protect \APACyear {2008}}%
	}]{%
		Macfarlane08}
	\APACinsertmetastar {%
		Macfarlane08}%
	\begin{APACrefauthors}%
		Macfarlane, B.%
		\BCBT {}\ \BBA {} Cheng, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2008}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Communism, Universalism and Disinterestedness:
		{R}e-examining Contemporary Support among Academics for {M}erton’s
		Scientific Norms} {Communism, universalism and disinterestedness:
		{R}e-examining contemporary support among academics for {M}erton’s
		scientific norms}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Academic Ethics}{6}{}{67--78}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s10805-008-9055-y} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Malka%
		, Lelkes%
		, Srivastava%
		, Cohen%
		\BCBL {}\ \BBA {} Miller%
	}{%
		Malka%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2012}}%
	}]{%
		Malka12}
	\APACinsertmetastar {%
		Malka12}%
	\begin{APACrefauthors}%
		Malka, A.%
		, Lelkes, Y.%
		, Srivastava, S.%
		, Cohen, A\BPBI B.%
		\BCBL {}\ \BBA {} Miller, D\BPBI T.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The Association of Religiosity and Political
		Conservatism: The Role of Political Engagement} {The association of
		religiosity and political conservatism: The role of political
		engagement}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Political Psychology}{33}{}{275--299}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Marchesini%
	}{%
		Marchesini%
	}{%
		{\protect \APACyear {2015}}%
	}]{%
		Marchesini15}
	\APACinsertmetastar {%
		Marchesini15}%
	\begin{APACrefauthors}%
		Marchesini, R.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Against Anthropocentrism. {N}on-human Otherness and the
		Post-human Project} {Against anthropocentrism. {N}on-human otherness and the
		post-human project}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{NanoEthics}{9}{}{75--84}.
	\newblock
	\begin{APACrefDOI} \doi{10.1007/s11569-015-0220-7} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Matthews%
	}{%
		Matthews%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Matthews17}
	\APACinsertmetastar {%
		Matthews17}%
	\begin{APACrefauthors}%
		Matthews, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	\APACrefbtitle {Donald {T}rump has tweeted climate change skepticism 115 times.
		{H}ere's all of it.} {Donald {T}rump has tweeted climate change skepticism
		115 times. {H}ere's all of it.}
	\newblock
	\begin{APACrefURL}
		\url{https://www.vox.com/policy-and-politics/2017/6/1/15726472/trump-tweets-global-warming-paris-climate-agreement}
	\end{APACrefURL}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Melby-Lerv{\aa}g%
		\ \BBA {} Hulme%
	}{%
		Melby-Lerv{\aa}g%
		\ \BBA {} Hulme%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		MelbyLervag16}
	\APACinsertmetastar {%
		MelbyLervag16}%
	\begin{APACrefauthors}%
		Melby-Lerv{\aa}g, M.%
		\BCBT {}\ \BBA {} Hulme, C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {There is no convincing evidence that working memory
		training is effective: {A} reply to {A}u et al. (2014) and {K}arbach and
		{V}erhaeghen (2014)} {There is no convincing evidence that working memory
		training is effective: {A} reply to {A}u et al. (2014) and {K}arbach and
		{V}erhaeghen (2014)}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychonomic Bulletin {\&} Review}{23}{}{324--330}.
	\newblock
	\begin{APACrefDOI} \doi{10.3758/s13423-015-0862-z} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Merton%
	}{%
		Merton%
	}{%
		{\protect \APACyear {1942}}%
	}]{%
		Merton42}
	\APACinsertmetastar {%
		Merton42}%
	\begin{APACrefauthors}%
		Merton, R\BPBI K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1942}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The Normative Structure of Science} {The normative
		structure of science}.{\BBCQ}
	\newblock
	\BIn{} N.~Storer\ (\BED), \APACrefbtitle {The sociology of science:
		{T}heoretical and empirical investigations} {The sociology of science:
		{T}heoretical and empirical investigations}\ (\BPGS\ 267--278).
	\newblock
	\APACaddressPublisher{Chicago}{The University of Chicago Press}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Milfont%
		, Richter%
		, Sibley%
		, Wilson%
		\BCBL {}\ \BBA {} Fischer%
	}{%
		Milfont%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2013}}%
	}]{%
		Milfont13}
	\APACinsertmetastar {%
		Milfont13}%
	\begin{APACrefauthors}%
		Milfont, T\BPBI L.%
		, Richter, I.%
		, Sibley, C\BPBI G.%
		, Wilson, M\BPBI S.%
		\BCBL {}\ \BBA {} Fischer, R.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Environmental Consequences of the Desire to Dominate and
		Be Superior} {Environmental consequences of the desire to dominate and be
		superior}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Personality and Social Psychology
		Bulletin}{39}{}{1127--1138}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0146167213490805} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		J\BPBI D.~Miller%
		, Scott%
		\BCBL {}\ \BBA {} Okamoto%
	}{%
		J\BPBI D.~Miller%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2006}}%
	}]{%
		Miller06c}
	\APACinsertmetastar {%
		Miller06c}%
	\begin{APACrefauthors}%
		Miller, J\BPBI D.%
		, Scott, E\BPBI C.%
		\BCBL {}\ \BBA {} Okamoto, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2006}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Public acceptance of evolution} {Public acceptance of
		evolution}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Science}{313}{}{765--766}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		L.~Miller%
		\ \BBA {} Seligman%
	}{%
		L.~Miller%
		\ \BBA {} Seligman%
	}{%
		{\protect \APACyear {1999}}%
	}]{%
		Miller99}
	\APACinsertmetastar {%
		Miller99}%
	\begin{APACrefauthors}%
		Miller, L.%
		\BCBT {}\ \BBA {} Seligman, M\BPBI E\BPBI P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1999}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Beliefs about Responsibility and Improvement Associated
		with Liberal-Conservative Justice Beliefs} {Beliefs about responsibility and
		improvement associated with liberal-conservative justice beliefs}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological Reports}{84}{}{329-338}.
	\newblock
	\begin{APACrefDOI} \doi{10.2466/pr0.1999.84.1.329} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Mooney%
	}{%
		Mooney%
	}{%
		{\protect \APACyear {2011}}%
	}]{%
		Mooney11W}
	\APACinsertmetastar {%
		Mooney11W}%
	\begin{APACrefauthors}%
		Mooney, C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2011}{June}{}.
	\newblock
	\APACrefbtitle {The Science of Why We Don't Believe Science.} {The science of
		why we don't believe science.}
	\newblock
	\begin{APACrefURL}
		\url{http://motherjones.com/politics/2011/03/denial-science-chris-mooney}
	\end{APACrefURL}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Morrison%
		, Duncan%
		\BCBL {}\ \BBA {} Parton%
	}{%
		Morrison%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Morrison15}
	\APACinsertmetastar {%
		Morrison15}%
	\begin{APACrefauthors}%
		Morrison, M.%
		, Duncan, R.%
		\BCBL {}\ \BBA {} Parton, K.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Religion Does Matter for Climate Change Attitudes and
		Behavior} {Religion does matter for climate change attitudes and
		behavior}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLOS ONE}{10}{}{e0134868}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pone.0134868} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Osborne%
		\ \BBA {} Waters%
	}{%
		Osborne%
		\ \BBA {} Waters%
	}{%
		{\protect \APACyear {2002}}%
	}]{%
		Osborne02}
	\APACinsertmetastar {%
		Osborne02}%
	\begin{APACrefauthors}%
		Osborne, J\BPBI W.%
		\BCBT {}\ \BBA {} Waters, E.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2002}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Four Assumptions Of Multiple Regression That Researchers
		Should Always Test} {Four assumptions of multiple regression that researchers
		should always test}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Practical Assessment, Research and Evaluation}{8}{2}{}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Pfattheicher%
		\ \BBA {} Schindler%
	}{%
		Pfattheicher%
		\ \BBA {} Schindler%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		Pfattheicher16}
	\APACinsertmetastar {%
		Pfattheicher16}%
	\begin{APACrefauthors}%
		Pfattheicher, S.%
		\BCBT {}\ \BBA {} Schindler, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Misperceiving Bullshit as Profound Is Associated with
		Favorable Views of {C}ruz, {R}ubio, {T}rump and Conservatism} {Misperceiving
		bullshit as profound is associated with favorable views of {C}ruz, {R}ubio,
		{T}rump and conservatism}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLoS ONE}{11}{}{e0153419}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pone.0153419} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Polderman%
		\ \protect \BOthers {.}}{%
		Polderman%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2015}}%
	}]{%
		Polderman15}
	\APACinsertmetastar {%
		Polderman15}%
	\begin{APACrefauthors}%
		Polderman, T\BPBI J\BPBI C.%
		, Benyamin, B.%
		, de Leeuw, C\BPBI A.%
		, Sullivan, P\BPBI F.%
		, van Bochoven, A.%
		, Visscher, P\BPBI M.%
		\BCBL {}\ \BBA {} Posthuma, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2015}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Meta-analysis of the heritability of human traits based
		on fifty years of twin studies} {Meta-analysis of the heritability of human
		traits based on fifty years of twin studies}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Nature Genetics}{47}{}{702--709}.
	\newblock
	\begin{APACrefDOI} \doi{10.1038/ng.3285} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Polonsky%
		, Vocino%
		, Grimmer%
		\BCBL {}\ \BBA {} Miles%
	}{%
		Polonsky%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2014}}%
	}]{%
		Polonsky14}
	\APACinsertmetastar {%
		Polonsky14}%
	\begin{APACrefauthors}%
		Polonsky, M\BPBI J.%
		, Vocino, A.%
		, Grimmer, M.%
		\BCBL {}\ \BBA {} Miles, M\BPBI P.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2014}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The interrelationship between temporal and environmental
		orientation and pro-environmental consumer behaviour} {The interrelationship
		between temporal and environmental orientation and pro-environmental consumer
		behaviour}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{International journal of consumer
		studies}{38}{}{612--619}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Porter%
	}{%
		Porter%
	}{%
		{\protect \APACyear {2013}}%
	}]{%
		Porter13}
	\APACinsertmetastar {%
		Porter13}%
	\begin{APACrefauthors}%
		Porter, C.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Liberalism, Optimism, and Utopia} {Liberalism, optimism,
		and utopia}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{International Trade \& Business Law Review}{16}{}{555}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Ranney%
		, Munnich%
		\BCBL {}\ \BBA {} Lamprey%
	}{%
		Ranney%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Ranney16a}
	\APACinsertmetastar {%
		Ranney16a}%
	\begin{APACrefauthors}%
		Ranney, M\BPBI A.%
		, Munnich, E\BPBI L.%
		\BCBL {}\ \BBA {} Lamprey, L\BPBI N.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Increased wisdom from the ashes of ignorance and
		surprise: {N}umerically-driven inferencing, global warming, and other
		exemplar realms} {Increased wisdom from the ashes of ignorance and surprise:
		{N}umerically-driven inferencing, global warming, and other exemplar
		realms}.{\BBCQ}
	\newblock
	\BIn{} B\BPBI H.~Ross\ (\BED), \APACrefbtitle {The psychology of learning and
		motivation} {The psychology of learning and motivation}\ (\BVOL~65, \BPGS\
	129--182).
	\newblock
	\APACaddressPublisher{New York}{Elsevier}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/bs.plm.2016.03.005} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Rattan%
		, Savani%
		, Naidu%
		\BCBL {}\ \BBA {} Dweck%
	}{%
		Rattan%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2012}}%
	}]{%
		Rattan12}
	\APACinsertmetastar {%
		Rattan12}%
	\begin{APACrefauthors}%
		Rattan, A.%
		, Savani, K.%
		, Naidu, N\BPBI V\BPBI R.%
		\BCBL {}\ \BBA {} Dweck, C\BPBI S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Can everyone become highly intelligent? {C}ultural
		differences in and societal consequences of beliefs about the universal
		potential for intelligence.} {Can everyone become highly intelligent?
		{C}ultural differences in and societal consequences of beliefs about the
		universal potential for intelligence.}{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Personality and Social
		Psychology}{103}{}{787--803}.
	\newblock
	\begin{APACrefDOI} \doi{10.1037/a0029263} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Rohrbaugh%
		\ \BBA {} Jessor%
	}{%
		Rohrbaugh%
		\ \BBA {} Jessor%
	}{%
		{\protect \APACyear {1975}}%
	}]{%
		Rohrbaugh75}
	\APACinsertmetastar {%
		Rohrbaugh75}%
	\begin{APACrefauthors}%
		Rohrbaugh, J.%
		\BCBT {}\ \BBA {} Jessor, R.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{1975}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Religiosity in youth: A personal control against deviant
		behavior1} {Religiosity in youth: A personal control against deviant
		behavior1}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Personality}{43}{}{136--155}.
	\newblock
	\begin{APACrefDOI} \doi{10.1111/j.1467-6494.1975.tb00577.x} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Rosseel%
	}{%
		Rosseel%
	}{%
		{\protect \APACyear {2012}}%
	}]{%
		Rosseel12}
	\APACinsertmetastar {%
		Rosseel12}%
	\begin{APACrefauthors}%
		Rosseel, Y.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2012}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {{lavaan}: An {R} Package for Structural Equation
		Modeling} {{lavaan}: An {R} package for structural equation modeling}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Statistical Software}{48}{2}{1--36}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Rudman%
		, McLean%
		\BCBL {}\ \BBA {} Bunzl%
	}{%
		Rudman%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2013}}%
	}]{%
		Rudman13}
	\APACinsertmetastar {%
		Rudman13}%
	\begin{APACrefauthors}%
		Rudman, L\BPBI A.%
		, McLean, M\BPBI C.%
		\BCBL {}\ \BBA {} Bunzl, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {When Truth Is Personally Inconvenient, Attitudes Change
		The Impact of Extreme Weather on Implicit Support for Green Politicians and
		Explicit Climate-Change Beliefs} {When truth is personally inconvenient,
		attitudes change the impact of extreme weather on implicit support for green
		politicians and explicit climate-change beliefs}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological Science}{24}{}{2290--2296}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Rutjens%
		, Sutton%
		\BCBL {}\ \BBA {} van~der Lee%
	}{%
		Rutjens%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2018}}%
	}]{%
		Rutjens17}
	\APACinsertmetastar {%
		Rutjens17}%
	\begin{APACrefauthors}%
		Rutjens, B\BPBI T.%
		, Sutton, R\BPBI M.%
		\BCBL {}\ \BBA {} van~der Lee, R.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Not all skepticism is equal: Exploring the ideological
		antecedents of science acceptance and rejection} {Not all skepticism is
		equal: Exploring the ideological antecedents of science acceptance and
		rejection}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Personality and Social Psychology
		Bulletin}{44}{}{384--405}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0146167217741314} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Sauce%
		\ \BBA {} Matzel%
	}{%
		Sauce%
		\ \BBA {} Matzel%
	}{%
		{\protect \APACyear {2018}}%
	}]{%
		Sauce18}
	\APACinsertmetastar {%
		Sauce18}%
	\begin{APACrefauthors}%
		Sauce, B.%
		\BCBT {}\ \BBA {} Matzel, L\BPBI D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {The paradox of intelligence: {H}eritability and
		malleability coexist in hidden gene-environment interplay.} {The paradox of
		intelligence: {H}eritability and malleability coexist in hidden
		gene-environment interplay.}{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Psychological Bulletin}{144}{}{26--47}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Shermer%
	}{%
		Shermer%
	}{%
		{\protect \APACyear {2013}}%
	}]{%
		Shermer13W}
	\APACinsertmetastar {%
		Shermer13W}%
	\begin{APACrefauthors}%
		Shermer, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2013}{January}{}.
	\newblock
	\APACrefbtitle {The Liberals' War on Science.} {The liberals' war on science.}
	\newblock
	\begin{APACrefURL}
		\url{http://www.scientificamerican.com/\\article.cfm?id=the-liberals-war-on-science}
	\end{APACrefURL}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Smith%
		, Yarwood%
		\BCBL {}\ \BBA {} Salisbury%
	}{%
		Smith%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2007}}%
	}]{%
		Smith07b}
	\APACinsertmetastar {%
		Smith07b}%
	\begin{APACrefauthors}%
		Smith, A.%
		, Yarwood, J.%
		\BCBL {}\ \BBA {} Salisbury, D\BPBI M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2007}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Tracking mothers’ attitudes to {MMR} immunisation
		1996--2006} {Tracking mothers’ attitudes to {MMR} immunisation
		1996--2006}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Vaccine}{25}{}{3996--4002}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.vaccine.2007.02.071} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Srinivasan%
		\ \BBA {} Kasturirangan%
	}{%
		Srinivasan%
		\ \BBA {} Kasturirangan%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		Srinivasan16}
	\APACinsertmetastar {%
		Srinivasan16}%
	\begin{APACrefauthors}%
		Srinivasan, K.%
		\BCBT {}\ \BBA {} Kasturirangan, R.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Political ecology, development, and human
		exceptionalism} {Political ecology, development, and human
		exceptionalism}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Geoforum}{75}{}{125 -- 128}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.geoforum.2016.07.011} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Sterling%
		, Jost%
		\BCBL {}\ \BBA {} Pennycook%
	}{%
		Sterling%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Sterling16}
	\APACinsertmetastar {%
		Sterling16}%
	\begin{APACrefauthors}%
		Sterling, J.%
		, Jost, J\BPBI T.%
		\BCBL {}\ \BBA {} Pennycook, G.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Are neoliberals more susceptible to bullshit?} {Are
		neoliberals more susceptible to bullshit?}{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Judgment and Decision Making}{11}{}{352--360}.
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Strauss%
	}{%
		Strauss%
	}{%
		{\protect \APACyear {2016}}%
	}]{%
		Strauss16}
	\APACinsertmetastar {%
		Strauss16}%
	\begin{APACrefauthors}%
		Strauss, V.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{February}{}.
	\newblock
	\APACrefbtitle {Why in the world would rapper {B.o.B} think the {E}arth is
		flat? A quick science lesson.} {Why in the world would rapper {B.o.B} think
		the {E}arth is flat? a quick science lesson.}
	\newblock
	\begin{APACrefURL} \url{https://www.washingtonpost.com/news/
			\\answer-sheet/wp/2016/02/02/why-in-the-world-would-rapper-\\
			b-o-b-think-the-earth-is-flat-a-quick-science-lesson/} \end{APACrefURL}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Swire-Thompson%
		\ \BBA {} Lazer%
	}{%
		Swire-Thompson%
		\ \BBA {} Lazer%
	}{%
		{\protect \APACyear {2020}}%
	}]{%
		Swire20}
	\APACinsertmetastar {%
		Swire20}%
	\begin{APACrefauthors}%
		Swire-Thompson, B.%
		\BCBT {}\ \BBA {} Lazer, D.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2020}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Public Health and Online Misinformation: Challenges and
		Recommendations} {Public health and online misinformation: Challenges and
		recommendations}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Annual Review of Public Health}{41}{}{}.
	\newblock
	\begin{APACrefDOI} \doi{10.1146/annurev-publhealth-040119-094127}
	\end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Todorov%
		\ \BBA {} Mandisodza%
	}{%
		Todorov%
		\ \BBA {} Mandisodza%
	}{%
		{\protect \APACyear {2004}}%
	}]{%
		Todorov04}
	\APACinsertmetastar {%
		Todorov04}%
	\begin{APACrefauthors}%
		Todorov, A.%
		\BCBT {}\ \BBA {} Mandisodza, A\BPBI N.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2004}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Public opinion on foreign policy: The multilateral
		public that perceives itself as unilateral} {Public opinion on foreign
		policy: The multilateral public that perceives itself as unilateral}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Public Opinion Quarterly}{68}{}{323-348}.
	\newblock
	\begin{APACrefDOI} \doi{10.1093/poq/nfh036} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Tranter%
		\ \BBA {} Lester%
	}{%
		Tranter%
		\ \BBA {} Lester%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Tranter17}
	\APACinsertmetastar {%
		Tranter17}%
	\begin{APACrefauthors}%
		Tranter, B.%
		\BCBT {}\ \BBA {} Lester, L.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Climate patriots? {C}oncern over climate change and
		other environmental issues in {A}ustralia} {Climate patriots? {C}oncern over
		climate change and other environmental issues in {A}ustralia}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Public Understanding of Science}{26}{}{738-752}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/0963662515618553} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Tullett%
		, Hart%
		, Feinberg%
		, Fetterman%
		\BCBL {}\ \BBA {} Gottlieb%
	}{%
		Tullett%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2016}}%
	}]{%
		Tullett16}
	\APACinsertmetastar {%
		Tullett16}%
	\begin{APACrefauthors}%
		Tullett, A\BPBI M.%
		, Hart, W\BPBI P.%
		, Feinberg, M.%
		, Fetterman, Z\BPBI J.%
		\BCBL {}\ \BBA {} Gottlieb, S.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2016}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Is ideology the enemy of inquiry? {E}xamining the link
		between political orientation and lack of interest in novel data} {Is
		ideology the enemy of inquiry? {E}xamining the link between political
		orientation and lack of interest in novel data}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Journal of Research in Personality}{63}{}{123 - 132}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.jrp.2016.06.018} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Warneken%
		, Hare%
		, Melis%
		, Hanus%
		\BCBL {}\ \BBA {} Tomasello%
	}{%
		Warneken%
		\ \protect \BOthers {.}}{%
		{\protect \APACyear {2007}}%
	}]{%
		Warneken07}
	\APACinsertmetastar {%
		Warneken07}%
	\begin{APACrefauthors}%
		Warneken, F.%
		, Hare, B.%
		, Melis, A\BPBI P.%
		, Hanus, D.%
		\BCBL {}\ \BBA {} Tomasello, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2007}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Spontaneous Altruism by Chimpanzees and Young Children}
	{Spontaneous altruism by chimpanzees and young children}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{PLOS Biology}{5}{}{e184}.
	\newblock
	\begin{APACrefDOI} \doi{10.1371/journal.pbio.0050184} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Warneken%
		\ \BBA {} Tomasello%
	}{%
		Warneken%
		\ \BBA {} Tomasello%
	}{%
		{\protect \APACyear {2006}}%
	}]{%
		Warneken06}
	\APACinsertmetastar {%
		Warneken06}%
	\begin{APACrefauthors}%
		Warneken, F.%
		\BCBT {}\ \BBA {} Tomasello, M.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2006}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Altruistic Helping in Human Infants and Young
		Chimpanzees} {Altruistic helping in human infants and young
		chimpanzees}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Science}{311}{}{1301--1303}.
	\newblock
	\begin{APACrefDOI} \doi{10.1126/science.1121448} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Washburn%
		\ \BBA {} Skitka%
	}{%
		Washburn%
		\ \BBA {} Skitka%
	}{%
		{\protect \APACyear {2018}}%
	}]{%
		Washburn17}
	\APACinsertmetastar {%
		Washburn17}%
	\begin{APACrefauthors}%
		Washburn, A\BPBI N.%
		\BCBT {}\ \BBA {} Skitka, L\BPBI J.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2018}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Science Denial Across the Political Divide} {Science
		denial across the political divide}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Social Psychological and Personality
		Science}{9}{}{972--980}.
	\newblock
	\begin{APACrefDOI} \doi{10.1177/1948550617731500} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Whitmarsh%
	}{%
		Whitmarsh%
	}{%
		{\protect \APACyear {2011}}%
	}]{%
		Whitmarsh11a}
	\APACinsertmetastar {%
		Whitmarsh11a}%
	\begin{APACrefauthors}%
		Whitmarsh, L.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2011}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Scepticism and uncertainty about climate change:
		{D}imensions, determinants and change over time} {Scepticism and uncertainty
		about climate change: {D}imensions, determinants and change over
		time}.{\BBCQ}
	\newblock
	\APACjournalVolNumPages{Global Environmental Change}{21}{}{690 -- 700}.
	\newblock
	\begin{APACrefDOI} \doi{10.1016/j.gloenvcha.2011.01.016} \end{APACrefDOI}
	\PrintBackRefs{\CurrentBib}
	
	\bibitem [\protect \citeauthoryear {%
		Winegard%
		\ \BBA {} Winegard%
	}{%
		Winegard%
		\ \BBA {} Winegard%
	}{%
		{\protect \APACyear {2017}}%
	}]{%
		Winegard17}
	\APACinsertmetastar {%
		Winegard17}%
	\begin{APACrefauthors}%
		Winegard, B.%
		\BCBT {}\ \BBA {} Winegard, B.%
	\end{APACrefauthors}%
	\unskip\
	\newblock
	\APACrefYearMonthDay{2017}{}{}.
	\newblock
	{\BBOQ}\APACrefatitle {Paranoid egalitarian meliorism: An account of bias in
		the social sciences} {Paranoid egalitarian meliorism: An account of bias in
		the social sciences}.{\BBCQ}
	\newblock
	\BIn{} J\BPBI T.~Crawford\ \BBA {} L.~Jussim\ (\BEDS), \APACrefbtitle {Politics
		of social psychology} {Politics of social psychology}\ (\BPGS\ 203--219).
	\newblock
	\APACaddressPublisher{}{Psychology Press}.
	\PrintBackRefs{\CurrentBib}
	
\end{thebibliography}


\end{document}
